### ISSUE TITLE
repeat media player control icon

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#1029]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am implementing displaycard with alexa sdk 1.9, when play flash briefing , there was PlayerInfoCard with repeat control toggle to render , but I can't find repeat icon in https://developer.amazon.com/zh/docs/alexa-voice-service/display-cards-tvs.html
## What is the expected behavior?

I want some repeat icon to render in GUI.
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello DonghuaZheng,

Thank you for bringing this to our attention!  We will look in to it.

Best regards,
-SWH

**Comment by DonghuaZheng** [comment]
Hi, you can get templaeRuntime visual metadata from function GuiRenderer::renderTemplateCard in SampleApp/src/GuiRenderer.cpp, then parse the the data via rapidjson which has usage sample in the GuiRenderer.cpp, finally you can invoke your GUI to render it on the screen.

**Comment by DonghuaZheng** [comment]
@scotthea-amazon Hi, how long I can get the repeat icon?

**Comment by Piflyer** [comment]
Ok, thanks!

**Comment by scotthea-amazon** [comment]
DonghuaZheng,

It looks like a simple omission in the documentation.  Luckily, it looks like you will not need to wait for the documentation to be corrected.  The links on the page you mentioned above:

https://developer.amazon.com/zh/docs/alexa-voice-service/display-cards-tvs.html#asseturls

...have a regular pattern.  For example, if you copy the link to the 1010pTV asset for 'Shuflle':

https://images-na.ssl-images-amazon.com/images/G/01/alexa/avs/gui/tv/1080pTV/control-shuffle-default.png

...and replace 'shuffle' with 'repeat' you will get the asset for the repeat button:

https://images-na.ssl-images-amazon.com/images/G/01/alexa/avs/gui/tv/1080pTV/control-repeat-default.png

Also, please contact us here: [Contact AVS Device SDK Team](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and refer to this issue in the comments you provide so that we can follow up with you privately.

Thank you,
-SWH

**Comment by DonghuaZheng** [comment]
@scotthea-amazon thanks!
