### ISSUE TITLE
Bluetooth not specific in wiki

### ISSUE THREAD

**Issue by Tomoli75** [alexa/avs-device-sdk#1042]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
It shows the dependencies yet nothing else!

## What is the expected behavior?
Give instruction on setting up Bluetooth.

## What behavior are you observing?
Just the dependencies are shown.

## Provide the steps to reproduce the issue, if applicable:
N/A

### What version of the AVS Device SDK are you using?
      N/A

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X] Other - tell us more: n/a

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more: n/a

**Comment by kjkh** [comment]
Hi @Tomoli75,

Which platform are you running on? Some example of more detailed guides:

- [Ubuntu](https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide#bluetooth)
- [Generic Linux](https://github.com/alexa/avs-device-sdk/wiki/Linux-Reference-Guide#bluetooth) 
- [Raspberry Pi](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script#bluetooth)

**Comment by Tomoli75** [comment]
That raspberry pi section doesn't actually fully explain it. How do I activate it just using pi.sh or setup.sh?

**Comment by Tomoli75** [comment]
To add - Does Amazon music work on this, or do I have to use the previously mentioned Bluetooth?

**Comment by kclchan** [comment]
Hi @Tomoli75, the pi.sh doesn't not enable Bluetooth option by default.  You may want to modify the script so that the BLUETOOTH_BLUEZ option is turned on:
https://github.com/alexa/avs-device-sdk/wiki/Build-Options#build-with-bluetooth
But please be sure that all the mentioned bluetooth dependencies are installed.

As for Amazon Music, please note that Access to Amazon Music is currently restricted to Alexa-enabled devices that are approved for commercial distribution and use. Please contact your Amazon Business Development Representative to get started on the approval for Amazon Music.

**Comment by Tomoli75** [comment]
I'm just an individual though?

**Comment by Tomoli75** [comment]
So spotify works?

**Comment by Tomoli75** [comment]
(also, for anyone looking at this needing bluetooth, use my fork's install, as that comes with bluetooth as standard on raspberry pi's)

**Comment by kclchan** [comment]
Hi @Tomoli75, the SDK doesn't support Spotify by default.  You could use it to play other music service provider though, like TuneIn, iHeartRadio, etc.  Hope this helps!

**Comment by kjkh** [comment]
Closing issue as questions have been answered. If you have any further questions, please feel free to re-open.
