### ISSUE TITLE
How can I test the PlaybackController Interface?

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#106]
Hi,
We're trying to implement the support of all AVS interfaces in our test app, I can see the [doc](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/playbackcontroller)  about the interface, and I followed the message format to send but lack of **_context_** value like below:

**{"context": [],"event": {"header": {"namespace": "PlaybackController","name": "PauseCommandIssued","messageId": "d68bef73-beb9-4ed7-bcd5-1601b05d5614"},"payload": {}}}**

here I'm playing a music by "Alexa, play kissFM on iHeartRadio" or "Alexa, sing me a song", but when I send the message above to AVS, the music doesn't pause or stop, what is my mistake? 

and other messages are also failed:

    {"context": [],"event": {"header": {"namespace": "PlaybackController","name": "PlayCommandIssued","messageId": "22d760e4-4b13-4a08-8965-cfc8e3a4e772"},"payload": {}}}

    {"context": [],"event": {"header": {"namespace": "PlaybackController","name": "PreviousCommandIssued","messageId": "c65dda81-7357-4ebd-892d-3f6cbe9be4db"},"payload": {}}}

    {"context": [],"event": {"header": {"namespace": "PlaybackController","name": "NextCommandIssued","messageId": "6de2ee86-b23d-4bd8-9fc7-c5b739c39afa"},"payload": {}}}

Can someone tell me how can I test the PlaybackController Interface? please advise in details.

Thank you.

**Comment by kencecka** [comment]
Hi Boyce,

This is most likely failling because the `PlaybackController.PauseCommandIssued` event you are sending is incomplete; the context you have provided is empty.  To send correct context, you will want to call `ContextManagerInterface::getContext() `, and then wait for the callback to `ContextRequesterInterface::onContextAvailable()`, which will give you the context you should be sending with your `PlaybackController.PauseCommandIssued`.

Ken

**Comment by boyce-xx** [comment]
Hi @kencecka ,
    Thank you, another question: who will take liability for the context's state update? in other words, who will update the state of client components, AVS sdk or myself?
