### ISSUE TITLE
what is the directive flow when customer ask alexa to play music in AVS Device SDK

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#1074]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I ask alexa to play music, AVS Device SDK receive a speak directive to SpeechSynthesizer with a audio attachment, then SpeechSynthesizer finish the speech, AVS Device SDK receive a play directive to AudioPlayer with a url, then receive a RenderPlayerInfoCard when music playback is started. So music playback in AVS Device SDK seems pretty slow.

But in echo show , when I ask it to play music, the behavior is different, I can see that echo show start caching PlayerInfocard UI data when SpeechSynthesizer is playing speech, I guess it is caching music audio data at the same time. So music playback in echo show is very fast. 

Here is my question, in AVS Device SDK, does the play directive does not send unitl AVS receive SpeechSynthesizer PlaybackFinished event? Does the RenderPlayerInfo directive does not send unitl AVS receive AudioPlayer PlaybackStared event?

Here is my log：
[log.txt](https://github.com/alexa/avs-device-sdk/files/2587842/log.txt)

## What is the expected behavior?

For best customer experience, when SpeechSynthesizer  is handling speak directive, play and RenderPlayerInfo directive should be received by AVS Device SDK at the same time, So the AVS Device SDK can start caching audio data and gui data.
## What behavior are you observing?

speak, play and RenderPlayerInfo directive is received one by one unitl last direcive is handled.
## Provide the steps to reproduce the issue, if applicable:

ask  AVS Device SDK to play music , then observe alexa behavior and see debug log.
### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more:  STB

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by yanggewei** [comment]
@aumatsui 
thanks for your answer，now the best way I can find to reduce the time It consume before starting play music is buffering music data when the SpeechSynthesizer is speaking, now I have three questions
1. you say "at this point this is a known limitation and we are already tracking this issue", can you provide more information about the limitation?
2. since there is limitation, why echo show can cache music data when the SpeechSynthesizer is speaking?
3. can I modify the avs sdk to buffering music data when the SpeechSynthesizer is speaking?
looking forward to your reply，thank you.

**Comment by dhpp** [comment]
Hi @yanggewei, thanks for your follow up questions.  The limitation mentioned above is an artifact of the AVS protocol - the AudioPlayer.Play Directive is sent once Alexa's speech has finished, so there is not much opportunity to buffer audio ahead of time.  I expect that Amazon's devices, which don't use AVS internally, may have different protocols at this time.  However, it is on our roadmap to converge the behavior.  At this time I'm not sure there is a way to optimize the SDK's behavior, since it depends on the sequence in which AVS sends the Directives.

**Comment by dhpp** [comment]
I'll close this ticket for now, as I don't think there is more to add from the SDK perspective.
