### ISSUE TITLE
genConfig.sh: File o directory does not exist

### ISSUE THREAD

**Issue by Ismaele87** [alexa/avs-device-sdk#1077]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

hello to everybody, once I execute te command:

cd /home/pi/
sudo bash setup.sh config.txt

the installation goes fine until
==============> SAVING CONFIGURATION FILE ==============

bash: genConfig.sh: File o directory do not exist

## What behavior are you observing?

Furthermore at the beginning of the installation when I have to execute

wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/setup.sh && wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/config.txt && wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/pi.sh

It does not create the file config.txt and I have to create manually

### What version of the AVS Device SDK are you using?
    I don't know exactly

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by aumatsui** [comment]
Hi Ismaele87,

The wget command is not working because the config.txt does not exist on the latest from master.

So it looks like you are running an old version of the SDK. It would be great if you could specify the version for us to understand which script you are running.

Regarding this issue:

```
bash: genConfig.sh: File o directory do not exist
````

It looks like bash is trying to run `genConfig.sh` but such script is not on the current directory. Can you make sure that `/home/pi/` contains this file? If not, then you would need to CD to this directory first.

**Comment by Ismaele87** [comment]
it should be v1.10.0 released 10/24/2018, checked on /home/pi/avs-device-sdk/readme.md, I don't how how to identificate SDK version via terminal.

I solved the problem with

genConfig.sh

I had to download from github repository and copied into /home/pi. Then I had to copy, in the same directory the file

config.json

After that it worked

Thanks
