### ISSUE TITLE
InternetConnectionMonitor recovery failed after a long term disconnected

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1081]
Hi AVS team,

SDK 1.9.0.  ARM based embedded linux.

please check the log at line 34892.   there is an InternetConnectionMonitor report failed.
at this time, there is a problem from our ISP and cause all outside connection failed for about 20-30 minutes.  All connection to Amazon was failed includes Echo device. 

After that, everything return to normal, and some of AVS device return to be normal and working.
But this device, it did never return until now.
It's a known issue ? I saw there are other issues #824 , and #926 , not sure if it's the same case.

[internet_connection_fail.txt](https://github.com/alexa/avs-device-sdk/files/2597613/internet_connection_fail.txt)

**Comment by dhpp** [comment]
Hi @zeusshuang, the issue you're seeing may be related to something we fixed in our recent releases.  I see, per the formatting of the error trace you point to, that your code is based on this un-patched version.    If you look at our current implementation, per here:

https://github.com/alexa/avs-device-[sdk/blob/master/AVSCommon/Utils/src/Network/InternetConnectionMonitor.cpp#L135](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/Utils/src/Network/InternetConnectionMonitor.cpp#L135)

then you will see the difference.  @kclchan mentioned in #824 that this issue is now fixed in the 1.9 release (the SDK is now at 1.10).

We believe the issue should resolve your issue, but please let us know if it does not.

**Comment by kclchan** [comment]
Hi @zeusshuang, as mentioned in #1121, please try this again with v1.10 of the SDK.  There are some fixes made to LibCurlHttpContentFetcher in v1.10 where promises are not being fulfilled in some curl error conditions. Thanks!

**Comment by visayamv** [comment]
Hello, I will be closing this thread due to inactivity, but feel free to reopen if you need further assistance.
