### ISSUE TITLE
AVS and Smart Home device

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1093]
Hi AVS team,

I have a question about AVS and Smart Home device.
There are users complained about the it cannot control their "Philips HUE" smart light device while they switched to AVS device and turn off Echo. (make sure the same Alexa account)

I checked the "Philips HUE", it's a Alexa Skill to control the light devices, but I cannot make sure if it's only work on Echo only (maybe there is another tasks in Echo), and AVS cannot support such smart home devices ?

Could you have comments ?

Thanks,

**Comment by mavamazon** [comment]
Hey!
It sounds strange to me because I see no difference in use cases from Alexa perspective. Do you know if:
- it worked when talked to AVS device while Echo is online?
- it ever worked without Echo device?
- AVS device is working for other utterances like play music when Echo is offline?
- these devices are in MRM cluster? In this case Echo device might be the master one and AVS device did not realize it is now offline.

Do you have any logs? What I need is any recent request ID ("amzn....") from that customer and approximate time of the failure.

**Comment by zeusshuang** [comment]
Hi @mavamazon ,

it worked when talked to AVS device while Echo is online?
>> Yes. It's really strange.
it ever worked without Echo device?
>> No, users only have Echo and AVS device.
AVS device is working for other utterances like play music when Echo is offline?
>> Yes, all AVS services are working correctly. And it make sure it's the same Amazon account.
these devices are in MRM cluster? In this case Echo device might be the master one and AVS device did not realize it is now offline.
>> No MRM.  I am asking logs.

**Comment by celinval** [comment]
Hi @zeusshuang,

Were you able to get logs for this issue?

Thanks,

**Comment by zeusshuang** [comment]
Hi @celinval ,

We are asking users to provided logs and some answers.

**Comment by scotthea-amazon** [comment]
Hi @zeusshuang,

There has not been any activity on this issue for a log time.  Is it still an active concern?  Should we close it?

Thank you,
-SWH

**Comment by zeusshuang** [comment]
Hi @scotthea-amazon ,

We can close this case now.
