### ISSUE TITLE
Getting empty supportedInterfaces o lambda when using sample app

### ISSUE THREAD

**Issue by ecruzado** [alexa/avs-device-sdk#1139]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, when I test a skill with cards from the Alexa Developer Console, I got this request on my lambda: 

<img width="873" alt="screen shot 2018-12-24 at 9 02 17 am" src="https://user-images.githubusercontent.com/1858914/50401244-13f8c680-075b-11e9-9f60-744460a8624d.png">

but when I test the same skill from Sample App I get empty supported interfaces

<img width="836" alt="screen shot 2018-12-24 at 9 07 25 am" src="https://user-images.githubusercontent.com/1858914/50401296-81a4f280-075b-11e9-93d7-c3004f8af1e7.png">

 

## What is the expected behavior?

I should receive supported interfaces.

## What behavior are you observing?

Getting empty supported interfaces.

## Provide the steps to reproduce the issue, if applicable:

Execute any skill with cards using Sample App, and see context.device.supportedInterfaces on the request we get on lambda

### What version of the AVS Device SDK are you using?
      1.11.0

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi,

The C++ SDK currently supports receiving RenderingTemplate directives from AVS and this is published as such. The AVS cloud may require additional interfaces that the SDK does not currently support, which is why this list is showing up as empty. 

We will follow up with the cloud team to ensure that we are not under reporting any capabilities that the SDK may support.

**Comment by visayamv** [comment]
Hi @ecruzado , have you enabled template runtime and display cards for your account? Also you would need to enable displayCardsSupported in AlexaClientSDKConfig.json

**Comment by ecruzado** [comment]
Yes
 - I enabled the template runtime using the capabilities API
 - The skill has enabled the display interface.
 - DisplayCardsSupported set to true on AlexaClientSDKConfig.json.

I got cards on the console, but I am still getting empty supported interfaces on my lambda.

**Comment by dhpp** [comment]
@kjkh 's answer above is correct, because the C++ Client SDK is strictly an AVS client.  It may receive AVS Directives under all supported Interfaces, and we should not expect anything else on the cloud side to be reported to the client.  You certainly do seem to have display cards enabled correctly, as the default behavior of the SampleApp in this case is to print the contents to the screen (since each partner will have differing specialization per rendering on a given device).

It seems like your question may be better directed to the Skills team, as it appears to me that our SDK is doing the right thing.  I would suggest posting your question [here](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html).  In the meantime, I'll close this one out.
