### ISSUE TITLE
Questions about "INTERNAL_SERVICE_ERROR" event 

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1141]
Hi AVS team,

SDK 1.10/1.11 .  ARM based embedded linux system.  

I found something strange in Listening or Speaking state, AVS often receive "INTERNAL_SERVICE_ERROR" message and 500 result in these state.
While it happens in Listening state, it will jump to Idle directly and will not listen input audio.
While it happens in Speaking state, it will not play any audio and jump to Idle.

Could you advise if there is any missed or something wrong to get this status ?
I have a debug9 log for reference, you can just search this exception keyword in the log.

[internal_service_exception.zip](https://github.com/alexa/avs-device-sdk/files/2711240/internal_service_exception.zip)

**Comment by kjkh** [comment]
Hi @zeusshuang,

The exception you are seeing is because you are being throttled. I have contacted the cloud team and they mentioned that the requests coming from your devices are within expected values, so they are investigating. We will update the ticket when there is further information as to why the throttling is occurring.

**Comment by zeusshuang** [comment]
Hi @kjkh ,
We can close this case now. I have contacted with Amazon team and solved this problem.

**Comment by aumatsui** [comment]
Thank you for your feedback. Please let us know if you need further assistance.
