### ISSUE TITLE
Using Kitt_AI instead of Sensory

### ISSUE THREAD

**Issue by fraeggle** [alexa/avs-device-sdk#1162]
I'm going crazy.
I follow these instructions Raspberry Pi Quick Start Guide with Script.
How can I just switch to KITT_AI?
I've looked at all kinds of instructions, but somehow I can't handle it.
e.g. Raspberry Pi Quick Start Guide (https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide Build Options).

can someone help me in a simple and understandable way?
Thanks a lot

**Comment by aumatsui** [comment]
Hi fraeggle,

In order to be concise, the Raspberry Pi guide simply tells you to use Sensory.

If you want to use Kitt.AI instead, you need to run `cmake` again. I recommend creating another build folder for that since `/home/pi/sdk-folder/sdk-build` will already have everything configured for Sensory.

See the [instructions for Kitt.AI](https://github.com/alexa/avs-device-sdk/wiki/Build-Options#kittai) for more details.

In short, you need to:

1. Create a new build directory
2. Download [Kitt.AI](https://github.com/Kitt-AI/snowboy/)
3. [Install the BLAS library](https://github.com/alexa/avs-device-sdk/wiki/Build-Options#kittai) (Kitt.AI dependency).
4. Call `cmake` again on the new build directory passing the arguments: `-DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=<absolute-path>/snowboy-1.2.0/lib/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR`

Do not use the Sensory arguments on the `cmake` command above.

I will close this ticket, but please feel free to let us know if you need more guidance.

Thank you,

**Comment by yulonglovecode** [comment]
> Hi fraeggle,
> 
> In order to be concise, the Raspberry Pi guide simply tells you to use Sensory.
> 
> If you want to use Kitt.AI instead, you need to run `cmake` again. I recommend creating another build folder for that since `/home/pi/sdk-folder/sdk-build` will already have everything configured for Sensory.
> 
> See the [instructions for Kitt.AI](https://github.com/alexa/avs-device-sdk/wiki/Build-Options#kittai) for more details.
> 
> In short, you need to:
> 
>     1. Create a new build directory
> 
>     2. Download [Kitt.AI](https://github.com/Kitt-AI/snowboy/)
> 
>     3. [Install the BLAS library](https://github.com/alexa/avs-device-sdk/wiki/Build-Options#kittai) (Kitt.AI dependency).
> 
>     4. Call `cmake` again on the new build directory passing the arguments: `-DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=<absolute-path>/snowboy-1.2.0/lib/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR`
> 
> 
> Do not use the Sensory arguments on the `cmake` command above.
> 
> I will close this ticket, but please feel free to let us know if you need more guidance.
> 
> Thank you,

Currently Kitt.Ai has shut down their website and documentation on the configuration for raspberry pi . Is there any detailed steps to use Kitt.Ai with AVS on the raspberry pi ?
