### ISSUE TITLE
How to synchronize states of MediaPlayer  and Local player?

### ISSUE THREAD

**Issue by dreamforever** [alexa/avs-device-sdk#121]
We want to use our own Local Player to play cues and other music files. How to synchronize the status?
For example, we want to play cues like  "wifi disconnected" while the other music is  playing by MediaPlayer in AVS, how to stop or pause the MediaPlayer ?  After the cues finish playing, MediaPlayer have to resume. How to deal with this situation? thank you : )

**Comment by kencecka** [comment]
Hi @dreamforever,

This is a great question, and your use case is exactly what FocusManager (AFML) is designed for.  FocusManager is responsible for managing interactions between different audio channels so that the user experience is seamless and intuitive.

AVS specifically calls out three logical channels:
- Dialog
- Content
- Alerts

The FocusManager constructor defaults to creating these three channels, but you can modify the SDK to add additional channels for your own use cases, if the existing channels do not fit your needs.  In general, you want to choose an appropriate channel for your audio, and then acquire/release that channel when you want to play something.

Some relevant links:
- For choosing an appropriate channel, I would read the AVS documentation on channels, which you can find [here](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/interaction-model#channels).
- For more detail on the SDK implementation of channels, you can read about FocusManager [here](https://alexa.github.io/avs-device-sdk/classalexa_client_s_d_k_1_1afml_1_1_focus_manager.html).
- If you elect to add a custom channel, you will need to modify DefaultClient, as the channel list is not currently exposed.  DefaultClient instantiates FocusManager (here)[https://github.com/alexa/avs-device-sdk/blob/6ec9cc785ceb7e9b7e9ff9eaa7be6889d3309808/ApplicationUtilities/DefaultClient/src/DefaultClient.cpp#L110].  You would need to change that line to pass an extended list of channels, rather than using the default list.

Please reopen this issue if you have more general questions, or open a new one with any specific questions that come up while working through this.

Ken

**Comment by sundq** [comment]
two questions:

- your means to **modify the SDK**, but how to update the sdk if we modify the sdk
- can the `FocusManager` be inherited?  there is no virtual destructor.
- how I trigger the channels which I extend,  should I add a  **Capability Agent** for process the local directive
