### ISSUE TITLE
While playing alerts, If we say alexa, alert sound is not stopping immediately(playing for 2 seconds after wake-word detected).

### ISSUE THREAD

**Issue by vijay464** [alexa/avs-device-sdk#1224]
## What is the expected behavior?
While playing alerts, if user utters wake-word, Timer sound should stop immediately. 

## What behavior are you observing?
While playing alerts, If we say alexa, alert sound is not stopping immediately(playing for 2 seconds after wake-word detected).

## Provide the steps to reproduce the issue, if applicable:
This issue is reproducible every time in sdk version 1.10/1.11.
1. Register device with amazon
2. Set timer for 10 seconds
3. While playing timer say Alexa
4. Observe the timer playback.

## Tell us about your environment:
- [ ] AVS sdk version 1.10.

### Tell us what hardware you're using:
- [ ] Desktop

### Tell us about your OS (Type & version):
- [ ] Linux

Lof File:
[timer_issue.txt](https://github.com/alexa/avs-device-sdk/files/2855394/timer_issue.txt)

Thanks
Vijay

**Comment by womw** [comment]
Hey @vijay464 thanks for the post.

Regarding the expected behaviour, it should actually switch from playing the alert sound to playing the short alert sound every 10 seconds as documented in this [ux guideline](https://developer.amazon.com/docs/alexa-voice-service/ux-design-attention.html#alerts). You can see this happening in the logs in line 118 when the regular alert sound has stopped and at line 145 when the short alert sound is played. To see this in action try asking alexa "who is usain bolt" while an alert is playing and you will hear the short alert sound every 10 seconds.

I will be closing this issue, please feel free to reopen if you still have issues.

**Comment by vijay464** [comment]
Hi womw,

As you said 
"Alert actually switch from playing the alert sound to playing the short alert sound every 10 seconds as documented in this [ux guideline](https://developer.amazon.com/docs/alexa-voice-service/ux-design-attention.html#alerts)."

The same case i tried in all amazon echo devices. The result is
"whenever the wake-word detects while playing alert, the alert sound will stop immediately and after 10 seconds it will start as short alert sound."

But in my case,
"The alert is playing for two seconds after wake-word detection and then it is going for short alert sound every 10 seconds".

Thanks
Vijay

**Comment by womw** [comment]
I see, going to reopen and investigate into this issue, we'll update when we get more information.

**Comment by vijay464** [comment]
Hi womw,

Any update on this issue?

Thanks
Vijay

**Comment by visayamv** [comment]
Hi @vijay464 , we have opened an internal ticket to investigate this further.

**Comment by kjkh** [comment]
Hi @vijay464,

We have filed a bug to track this internally and it will be fixed in a future release. There are no updates as of right now.

**Comment by dhpp** [comment]
This has now been fixed and released in the SDK.  I'll close this ticket out.
