### ISSUE TITLE
While running SampleApp it doesn't show other require logs after device Authorized! with DEBUG9

### ISSUE THREAD

**Issue by Hitengit054** [alexa/avs-device-sdk#1237]
## What is the expected behavior?
Kindly inform you that i'm using cross platform **aarch64(Arm) linux**. I have cross-compiling all the dependencies library using this [link](https://github.com/alexa/avs-device-sdk/wiki/Dependencies)

## What behavior are you observing?
After authorised by code SampleApp will not give other logs i.e alsa lib audio input or output configuration or something else. So that i could not able to find out problem. It is showing libcurl log in interval of few mins. 

## Tell us about your environment:
      aarch64(Arm) linux

### What version of the AVS Device SDK are you using?
      sdkVersion: 1.11.0

### Tell us about your OS (Type & version):
- [y ] Linux
****
i have attach my DEBUG9 log and `AlexaClientSDKConfig.json`. for the security purpose i have removed the client id, product id and serial number from  `AlexaClientSDKConfig.json` file. Thanks 

[Issue_alexa_SampleApp.txt](https://github.com/alexa/avs-device-sdk/files/2880220/Issue_alexa_SampleApp.txt)
[AlexaClientSDKConfig.txt](https://github.com/alexa/avs-device-sdk/files/2880221/AlexaClientSDKConfig.txt)

**Comment by scotthea-amazon** [comment]
Hello Hitengit054,

It is not entirely clear from your description and logs what the problem is.  It appears that your SampleApp has successfully authorized.   The continuing logs every few minutes appear to be the normal periodic verification of internet connectivity.  I do not see any errors in the log.  

What does appear odd is:
1. The 'AVS SDK SampleApp' banner comment (a large block of ASCII art, followed by a help page showing options) is not apparent in your logs.
2. After authorization there are no logs from CapabilitiesDelegate or HTTP2Transport

Given that we see other logs from SampleApp, I am not sure how to account for (1).

(2) might be accounted for if for some reason SampleApplication::initialize() never made its way to the call to [client->connect()](https://github.com/alexa/avs-device-sdk/blob/v1.11/SampleApp/src/SampleApplication.cpp#L872).

It looks like you will need to track down where SampleApplication::initialize() is getting stuck.

Best regards,
-SWH

**Comment by Hitengit054** [comment]
Thanks for the help @scotthea-amazon 

for (2) i have tested this HTTP2TransportTest & CapabilitiesDelegateTest tests. Both got passed as per attach log. 
[HTTP2TransportTest.txt](https://github.com/alexa/avs-device-sdk/files/2900205/HTTP2TransportTest.txt)
[CapabilitiesDelegateTest.txt](https://github.com/alexa/avs-device-sdk/files/2900206/CapabilitiesDelegateTest.txt)

since 2 days, i try to debug SampleApp and i'm actually found where the SampleApp getting struck. 
I add some console log just for check as per below in [here](https://github.com/alexa/avs-device-sdk/blob/451e6056aee3b92a01e9b58d79f1f30a11625beb/SampleApp/src/SampleApplication.cpp#L765)

```
#ifdef PORTAUDIO
ACSDK_CRITICAL(LX("before PortAudioMicrophoneWrapper!")); // my changes
std::shared_ptr<PortAudioMicrophoneWrapper> micWrapper = PortAudioMicrophoneWrapper::create(sharedDataStream);
ACSDK_CRITICAL(LX("inside PortAudioMicrophoneWrapper!")); // my changes
```
I got console print of  `before PortAudioMicrophoneWrapper`  with Debug9. but i'm unable to get the print `inside PortAudioMicrophoneWrapper!`. Inside the `PortAudioMicrophoneWrapper.cpp` file, it is getting stuck in `portAudioMicrophoneWrapper->initialize()` function.  

can you provide more info in port audio section. ?? 
i have cross compile the port audio library --without-jack --without-oss --with-alsa.
I have checked my microphone.It is working  by Tinycap & arecord command.

**Comment by Hitengit054** [comment]
Thanks @scotthea-amazon i'm closing this issue.
