### ISSUE TITLE
Sever endpoint chaged event

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1243]
Hi AVS team,

SDK 1.9.0 , ARM based embedded linux.

I received a user's fail unit that the AVS always registered failed.
After dump the DEBUG9 log, it seems the AVS initially authentication success, but disconnected while receive "server endpoint changed". 
See my attached log line 219, and 648.
The user said it's registered by Japan account and set to JP local.
Anything I can check here, the settings are still there, I believe while it restore to default and reset authentication, it may return to normal.

Thanks,

[server_side_endpoint_change_2.log](https://github.com/alexa/avs-device-sdk/files/2899635/server_side_endpoint_change_2.log)

**Comment by kjkh** [comment]
Hi @zeusshuang,

It's interesting because after the SetEndpoint directive, a connection appears to have been established since events are getting sent. Some examples of sent events are SynchronizeState and RequestToken. I am seeing that the InternetConnectionMonitor does not recognize that a connection has been established, which needs to be further investigated.

Were there any other degraded behaviors that were reported?

**Comment by zeusshuang** [comment]
Hi @kjkh ,

for this fail unit, it ever switch to different amazon users (users from different region).
the fail unit is still here, is there anything I can dump for checking ?

**Comment by kjkh** [comment]
Hi @zeusshuang,

Sorry, do you mind clarifying what you mean by fail unit? What failure behavior are you seeing?

**Comment by zeusshuang** [comment]
Hi @kjkh ,

The fail device with settings is still keep without reset authentication, so the fail symptom is still reproducible while AVS startup.  
So if I can do something or add new debug log in AVS to get more information, I can try it.

**Comment by zeusshuang** [comment]
@kjkh  we can close this case, we found something wrong and gateway blocked the http port, it seems it will cause this fail.
