### ISSUE TITLE
Music does not start play

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1244]
Hi AVS team,

SDK 1.11.  ARM based embedded linux.
It's JP locale.

User complained that Alexa can recognize the voice command to play target Amazon music, after TTS, no music will be played. Continue to try the same command the fail rate is about 50%.
Each time, while it did not play anything, to check Alexa APP history, it's actually recognized the commands and the song name.

I attached a DEBUG5 log. 
You can see from line 44282, it failed several times, but finally it's played the song.
Could you have comments and anything I need to check with the user ?

[avs_dbg_log_music_not_start.txt](https://github.com/alexa/avs-device-sdk/files/2900652/avs_dbg_log_music_not_start.txt)

**Comment by zeusshuang** [comment]
Hi AVS team,

attached is another log from Spain user.  It's SDK 1.11.
By user's Alexa APP history, it's actually recognized play tune-in and also show the station name.
However, nothing was playing then.

You can check from line#78452 ,  2019-02-25 13:19:51.398  from WWE triggered.

[tune_in_play_failed.txt](https://github.com/alexa/avs-device-sdk/files/2905154/tune_in_play_failed.txt)

**Comment by kjkh** [comment]
Hi @zeusshuang,

Regarding the JP issue, there was the following error:

`2019-02-21 21:48:26.760 [ 1f] E CapabilityAgent:handleDirectiveFailed:reason=messageIdNotFound,messageId=c67a646b-6633-4c65-bfdb-54aa8b593301`

This came about because of an issue with processing the TemplateRuntime directive. This is the same cause as another issue that you previously reported https://github.com/alexa/avs-device-sdk/issues/1143. This should be fixed in 1.12. Would it be possible to upgrade to the latest version?

Regarding the Spain issue, the line you linked eventually leads to an AudioPlayer.Stop, which is why playback stops.

`2019-02-25 13:19:53.575 [ 1e] I DirectiveSequencer:onDirective:directive={"namespace\:"AudioPlayer"\,name\:"Stop"\,messageId\:"1b543744-a4c4-4652-b5eb-047ddcac1e4c"\,dialogRequestId\:"19341c16-5842-46b2-a0ac-db2f4929f357"}`

Is this the correct line?

**Comment by zeusshuang** [comment]
Hi @kjkh ,

Thanks for the comment, I will check SDK1.12.

For Spain user's case, I will let user to double check it again.  From the symptom, it seems a little same as JP user.

**Comment by zeusshuang** [comment]
Hi @kjkh ,

Is there any chance I can back port this fix to SDK1.11 ? It's only in TemplateRuntime.cpp ?

**Comment by kclchan** [comment]
Hi @zeusshuang, yes, the fix of this issue is in TemplateRuntime.cpp only.
