### ISSUE TITLE
Amazon wake work engine integration

### ISSUE THREAD

**Issue by amitpriye** [alexa/avs-device-sdk#1249]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I need to integrate Amazon wake word engine.As i have only binary file and header provided by my vendor.
But in repo folder KWD i only find keywordetector code for Sensory and KittAi only . 
Is there any plan to add Amazon Keywordetector handler and files ? or do you have Keywordetector code for Amazon WWE ?
Thanks 

### Tell us what hardware you're using:
Other - tell us more: -Android

### Tell us about your OS (Type & version):
 Linux

**Comment by kjkh** [comment]
Hi @amitpriye,

Instead of GitHub, a direct channel between your company and Amazon is more suitable for the contents of your question. Please contact your Amazon business representative directly. I am closing this issue and we are looking forward to continue working with you when you reach us through the other channel.
