### ISSUE TITLE
some question about isssue 121 

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#126]
about #121 issue I have some question:

- you means to **modify the SDK**, but how to upgrade the sdk if we modify the sdk

- can the FocusManager be inherited? there is no **virtual destructor**.

- how I trigger the channels which I extend, should I add a **Capability Agent** for process the local directive 
- can I implement this function without modify SDK , such as inherite sdk class to implement our own method, so can upgrade sdk easily later
- can you give a demo

**Comment by kencecka** [comment]
Hi @sundq,

> your means to modify the SDK, but how to upgrade the sdk if we modify the sdk

The DefaultClient class is provided as an example and a convenience.  It implements the functionality we expect most applications will need, but does not try to expose every possible configuration of the SDK.  For cases such as yours, where you want to use something not exposed in DefaultClient, you can copy the DefaultClient code into your application and modify the copy.  Since this modified code lives outside the SDK, you are free to upgrade the SDK without overwriting your modified code.

> can the FocusManager be inherited? there is no virtual destructor.

FocusManager is not intended to be inherited.  It already allows you to specify the list of channels as a constructor parameter, so there should not be any need to inherit from it.

> how I trigger the channels which I extend, should I add a Capability Agent for process the local directive

Channels are triggered by calling m_focusManager->acquireChannel() and m_focusManager->releaseChannel().  To use your custom channels, you would need to
* pass the m_focusManager shared_ptr to your custom code so that it can call acquireChannel() and releaseChannel()
* implement a ChannelObserverInterface object which you can use to detect focus changes
You can see examples of this in CapabilityAgent implementations in the SDK, although you don't necessarily need to implement a full CapabilityAgent.  A CapabilityAgent implements a number of different interfaces which you may not need.  In particular, CapabilityAgents are DirectiveHandlers, and you likely are not going to be receiving directives from AVS in your custom code.

> can I implement this function without modify SDK , such as inherite sdk class to implement our own method, so can upgrade sdk easily later

As described above, you should make a copy of DefaultClient and modify it outside of the SDK.  As we see more custom use cases like this, we will work to make DefaultClient easier to extend in future releases, but copying it and modifying it is your best option today.

> can you give a demo

Here is a quick example of what you  might do.  This is not complete, but should give the general idea.  For more detailed examples, take a look at the CapabilityAgent implementations in the SDK to see how the interact with FocusManager.

```
class SundqCustomChannelUser : public ChannelObserverInterface {
public:
    SundqCustomChannelUser(std::shared_ptr<FocusManager> focusManager) : m_focusManager{focusManager} {
    }

    void playSomething() {
        m_focusManager->acquireChannel(SUNDQ_CUSTOM_CHANNEL_NAME, shared_from_this(), "SundqCustomChannelUser::playSomething");
    }

    void stopPlaying() {
        m_focusManager->releaseChannel(SUNDQ_CUSTOM_CHANNEL_NAME, shared_from_this());
    }

    void onFocusChanged(avs::FocusState newFocus) override {
        switch(newFocus) {
            case FOREGROUND:
                // start or resume playing
                break;
             case BACKGROUND:
                // pause playing
                break;
            case NONE:
                // stop playing
                break;
        }
    }

private:
    std::shared_ptr<FocusManageR> m_focusManager;
};

bool SundqCustomClient::initialize(...) {
    ...
    std::vector<ChannelConfiguration> channelConfigurations = {
            {DIALOG_CHANNEL_NAME, DIALOG_CHANNEL_PRIORITY}, 
            {ALERTS_CHANNEL_NAME, ALERTS_CHANNEL_PRIORITY}, 
            {CONTENT_CHANNEL_NAME, CONTENT_CHANNEL_PRIORITY},
            {SUNDQ_CUSTOM_CHANNEL_NAME, SUNDQ_CUSTOM_CHANNEL_PRIORITY}
    };
    m_focusManager = std::make_shared<afml::FocusManager>(channelConfigurations);
    ...
    m_sundqCustomChannelUser = std::make_shared<SundqCustomChannelUser>(m_focusManager);
    ...
}
```

Ken

**Comment by sundq** [comment]
Thank you very much
