### ISSUE TITLE
AVS Reply: What is the reply from server when I ask "Alexa, Who are you"

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#1263]
Hello AVS Team,

I want to know of the Alexa response  from the server when I asks a question "Alexa, Who are you"

Currently It is replying "I am Alexa" and it stops.

Can you please provide me the correct and complete desired response from alexa for this query

SDK Version - 1.9

**Comment by kclchan** [comment]
Hi @sumit3817, I just tested it myself and I am getting the same reply too.  Please note that the answer is generated in AVS and may change over time.

**Comment by zeusshuang** [comment]
Hi @kclchan ,

I also have this problem and question. It seems, from AVS SDK, it will always reply this simple answer; however, from Echo, I never got such short term answer.
Does AVS SDK connect to different server ?

**Comment by pankajitkaushik** [comment]
> Hi @sumit3817, I just tested it myself and I am getting the same reply too. Please note that the answer is generated in AVS and may change over time.

Hi @kclchan 

Does Amazon Echo reached to a different AVS SDK, because its providing a different resposne, even if i am logged in with same user account.

**Comment by aumatsui** [comment]
The response is completely generated by AVS, which has information about the device that is making the request, so AVS may decide to give different answers depending on the kind of device where the request originated.

**Comment by pankajitkaushik** [comment]
Somehow Echo dot is responding a longer answer for Alexa Who Are You? However my custom device is only responding "I am Alexa"

**Comment by dhpp** [comment]
A quick comment on this - I expect that your device is detecting the audio 'Alexa' being spoken, and thus activating wake-word detection, so the device thinks a real user has said 'Alexa'.  In this case, the SDK will stop rendering Alexa's response (in which she says her own name), and instead starts listening on the microphone for the user's voice.
The way to fix this is to update your audio processing on the device to filter out the speaker output, which commercial Alexa-enabled devices all do.  We can't comment further on the technical details of this, since it falls outside the scope of the Alexa client software which we offer.  However, please refer to other tickets which have asked about this, such as #696, #1188, and #1020.
