### ISSUE TITLE
Not able to build MRM Modules in AVS SDK V1.12

### ISSUE THREAD

**Issue by xurenjun** [alexa/avs-device-sdk#1285]
Hi, Is there anyone who can help?

1)  When I try to build AVS with MRM modules, but I get some errors:

     *CMake Error at CapabilityAgents/MRM/CMakeLists.txt:10 (add_subdirectory):
      add_subdirectory given source "MRMHandler" which is not an existing
      directory.*

2) Open options:
    -DMRM=ON
    -DMRM_LIB_PATH=xxx
    -DMRM_INCLUDE_DIR=xxxx

3) I can see about "MRMHandler" in CMakeLists.txt :

    cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
    project(MRM LANGUAGES CXX)

    include(../../build/BuildDefaults.cmake)

    add_subdirectory("src")
    add_subdirectory("test")

    if (MRM)
        add_subdirectory("MRMHandler")
    endif()

    ??? But there is no such folder "MRMHandler" in the directory.

**Comment by dhpp** [comment]
Hi @xurenjun, thanks for this question.

The MRM Capability Agent is a specialized plugin for handling Multi-Room-Music, and requires a code patch from Amazon to complete the implementation.  Acquiring the patch requires some pre-validation with Amazon partner managers, since there are strict hardware requirements that must be met (since the given partner device must be capable of playing in sync with other AVS or Amazon Alexa devices).

If you would like to be in touch our business partner managers, please fill out the form can you please fill out the contact form [here](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and someone will be in touch with you.

**Comment by xurenjun** [comment]
@dhpp Thanks!  I have got it.
