### ISSUE TITLE
There is some ERROR log message when  wake up alexa when it paly music

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#129]
When I ask alexa play music, before the music finish , I wake up alexa again and ask `what's your name`，The answer play finished and then music begin paly, when the music finished, the app will emit ERROR log message as follows:

**2017-09-01 07:44:16.409 [  4] E AudioPlayer:onFocusChangedFailed:reason=timedout,cause=executorTimeout
2017-09-01 07:44:16.409 [  5] E AudioPlayer:onFocusChangedFailed:reason=timedout,cause=notFinished**

and I check the code in AudioPlayer.cpp at line 584， the code is:

```       
case FocusState::NONE:
            if (PlayerActivity::STOPPED == m_currentActivity) {
                break;
            }
            m_audioItems.clear();

            std::unique_lock<std::mutex> lock(m_playbackMutex);
            m_playbackFinished = false;

            /* Note: MediaPlayer::stop() calls onPlaybackFinished() synchronously, which results in a mutex deadlock
             * here if the lock his held for the executeStop() call.  Releasing the lock temporarily avoids the
             * deadlock.  If MediaPlayer is changed in the future to asynchronously call onPlaybackFinished (and
             * documented as such in MediaPlayerInterface), the unlock/lock calls can be removed. */
            lock.unlock();
            ACSDK_DEBUG9(LX("executeOnFocusChanged").d("action", "executeStop"));
            executeStop();
            lock.lock();

            if (!m_playbackConditionVariable.wait_for(lock, TIMEOUT, [this] { return m_playbackFinished; })) {
                ACSDK_ERROR(LX("onFocusChangedFailed").d("reason", "timedout").d("cause", "notFinished"));
            }
            break;
```

These code is called by `onPlaybackFinished` observer method,  but `onPlaybackFinished` method will set `m_playbackFinished` to `true` then will call `onFocuseChanged`, so I think you will never `wait_for` the `m_playbackFinished` is `true`, because you have set `m_playbackFinished ` to `false` at line 546

is it that?

**Comment by kencecka** [comment]
Hi @sundq,

Thanks for pointing this out.  It looks like this occurs at the end of any audio playback that runs to completion.  The general flaw here is that executeOnFocusChanged() currently assumes that a focus change to NONE is happening during playback, tries to stop the playback, and then waits for confirmation that it stopped.  The code needs to be modified to be aware of whether playback was already stopped at the time of the focus change so that it can skip the stop/wait.

I have filed a ticket internally to address this in a future release.  For the current release, these errors should be harmless and you can disregard them.

Ken

**Comment by kclchan** [comment]
Closing the issue.  Please re-open if you are still having issues.
