### ISSUE TITLE
An issue where the response to "Who are you" is truncated

### ISSUE THREAD

**Issue by nunokid** [alexa/avs-device-sdk#130]
I built avs sdk on ubuntu and succeeded in running AVS.

But if I request "who are you", AVS will stop responding after "I'm alexa ~ Blah blah.."

Other requests normally respond. In other words, the answer is played and then stopped in the middle.

Do you know this problem?

**Comment by kencecka** [comment]
Hi @nunokid,

If you have a wakeword detector enabled, this is most likely caused by lack of Acoustic Echo Cancellation (AEC).  When AVS responds "I'm alexa", the sound coming from the speaker is picked up by the microphone, and the wakeword detector triggers, which interrupts the speech and starts a new recognize event.

Most production devices would include an Audio Front End (AFE) which would perform AEC.  This is implemented by making the AFE aware of what is currently being played out the speaker, so that it can subtract that signal out of the streaming coming in from the microphone.

Ken

**Comment by nunokid** [comment]
Thanks
