### ISSUE TITLE
when i build curl

### ISSUE THREAD

**Issue by sunjunlishi** [alexa/avs-device-sdk#135]
#../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_set_alpn_protos'
../lib/.libs/libcurl.so: undefined reference to `SSL_COMP_free_compression_methods'
../lib/.libs/libcurl.so: undefined reference to `SSL_get0_alpn_selected'

and i have build ssl
cp libcrypto.pc /home/pi/local-builds/lib/pkgconfig
chmod 644 /home/pi/local-builds/lib/pkgconfig/libcrypto.pc
cp libssl.pc /home/pi/local-builds/lib/pkgconfig
chmod 644 /home/pi/local-builds/lib/pkgconfig/libssl.pc
cp openssl.pc /home/pi/local-builds/lib/pkgconfig
chmod 644 /home/pi/local-builds/lib/pkgconfig/openssl.pc

**Comment by scotthea-amazon** [comment]
Hi Subjunlishi,

I don't think we have enough information in your post to really diagnose this issue.  Also, since you are building curl, you will probably get more expert advice from curl's github forum.  For example, searching for the error message in your post I found this thread:
[curl does not compile with openssl path and no pkg-config installed](https://github.com/curl/curl/issues/1128)

I hope this helps,
-SWH

**Comment by apatti** [comment]
I am also facing same issue while building it on the raspberry pi.

**Comment by mradulan** [comment]
Hi @sunjunlishi , did the issue resolve for you?

**Comment by kclchan** [comment]
Closing this issue.  Please feel free to re-open if you are still having issues.
