### ISSUE TITLE
selection of target Echo device for response

### ISSUE THREAD

**Issue by mduzgun** [alexa/avs-device-sdk#1365]
how to send request selecting target Echo device using AVS ? For example, using AVS, I want to send response to target device that is my physical Alexa echo plus.

**Comment by mvelegon-amzn** [comment]
Hi @mduzgun could you please give more information on how you are trying to send requests? Is this using the Alexa app? 

Also, I see that you already have a question opened on the AVS developer forums (https://forums.developer.amazon.com/questions/207033/selection-of-target-echo-device-for-response.html). As this issue is not related to AVS C++ SDK and is a more general question about AVS and Echo devices, I will be closing this issue in favor of the question on the developer forum. 

Please reopen if you need more information from the AVS C++ SDK perspective. 

Thanks!
