### ISSUE TITLE
E InProcessAttachmentReader:readFailed:reason=bytes requested smaller than SDS word size

### ISSUE THREAD

**Issue by yuan0258** [alexa/avs-device-sdk#1432]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Our voice preprocessing will generate 256 sample every 16ms from micphone & reference audio data.
And we will put the data into SDS stream
Sometime I will see this error message which is from https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/AVS/src/Attachment/InProcessAttachmentReader.cpp#L80

    auto wordSize = m_reader->getWordSize();
    if (numBytes < wordSize) {
        ACSDK_ERROR(LX("readFailed").d("reason", "bytes requested smaller than SDS word size"));
        *readStatus = ReadStatus::ERROR_BYTES_LESS_THAN_WORD_SIZE;
        return 0;
    }
It seems the device could wakeup normally
But I still want to know what's the meaning about this error message.
Does it mean the AIP want to request size is smaller than SDS store?

## What is the expected behavior?

No warning message

### What version of the AVS Device SDK are you using?
      <0.13.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [*] Other - tell us more: ARM CA7

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi @yuan0258, the trace you're seeing is defensive in nature, and ensures that audio data is not lost (since the underlying attachment code operates on fixed sizes of data for performance reasons).  If you are only seeing it occasionally, then I think you can safely ignore it, since on the next read the data will be consumed correctly.  I'll close this ticket out, please re-open if you'd like further comment.
