### ISSUE TITLE
Alexa Auto SDK , Android Sample not working Missing libraries 

### ISSUE THREAD

**Issue by vaibhav2800** [alexa/avs-device-sdk#1434]
## Briefly summarize your issue:
I am trying to build android Sample for Alexa AUTO Sdk(v1.6.1 released on 2019-06-21) as per instruction , but i am not able to build it. 
I am using **pre-built aace-release.aar** but not able to build project. 

## What is the expected behavior?
It should run properly.

## What behavior are you observing?
It is not working.

## Provide the steps to reproduce the issue, if applicable:
Download 

## Tell us about your environment:

Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 10, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Testing on Android Api levels 26-27-28

### What version of the AVS Device SDK are you using?
Alexa AUTO Sdk(v1.6.1 released on 2019-06-21)
     

### Tell us what hardware you're using:
- Laptop
- [ ] Other - tell us more:
For testing purpose i am using Android Device

**Comment by dhpp** [comment]
Hi @vaibhav2800, thanks for your question, however while the Alexa Auto SDK is based upon our SDK, we can't advise on Auto SDK issues.  We advise you bring your issue to them directly, since for example the library you mention is not something our team supports or has experience with.

I'll close this ticket out based on the above.
