### ISSUE TITLE
Build issues on Rapsberry pi

### ISSUE THREAD

**Issue by apatti** [alexa/avs-device-sdk#146]
While building code on the Raspberry pi i had following issues:

1. The instructions provided to build openssl from the source code doesn't work properly.  I had to cross compile openssl for raspberry pi.
2. Even though path was set correctly, still the old version of openssl was being used for other modules.
3. Building the sdk+app takes lot of time every time we make any small change. 

Did anyone face similar issues or am i missing something?

**Comment by sanjayrd** [comment]
Hi @apatti,

Thanks for the information. We haven't run into these issues, but we'll be going through the instructions, specifically regarding openssl over the next few days to see what might need to change.  The reason the build takes so long is because of the low processing power of the raspberry pi. This can be sped up by doing a `make -j3` or `make -j4`. We're also looking into changing or adding instructions for building on Raspbian Stretch, which should make everything much easier as many of the required packages will be able to be built simply by doing an `apt-get`.

Thanks,
Sanjay

**Comment by apatti** [comment]
Hi,

Thanks a lot, sanjay, would wait for the new update.
