### ISSUE TITLE
Bluetooth NOT connecting automatically after reboot or power cycle the Device

### ISSUE THREAD

**Issue by sphapale** [alexa/avs-device-sdk#1473]
## Briefly summarize your issue:
 AVS-SDK 1.14.0 - If user is connected over Bluetooth to Alexa Device and device gets rebooted or did power cycle then after successful device online, Alexa is working but it does not connect the Bluetooth device even if it is available.

## What is the expected behavior?
Mobile device should connect the Alexa device by default, if its connected before reboot/power cycle the Alexa.

## What behavior are you observing?
Mobile device is not connecting automatically after power cycle the Alexa, user needs to do it manually

## Provide the steps to reproduce the issue, if applicable:
1. Configure the Alexa
2. Connect Mobile over Bluetooth
3. Power cycle the Device
4. After Alexa online Bluetooth is not connected

## Tell us about your environment:
AVS SDK Version 1.14.0 Cross Compiled to run on below Hardware.
PulseAudio
Bluetooth
### What version of the AVS Device SDK are you using?
1.14.0

### Tell us what hardware you're using:

- [ ] Other - Hardware: Samsung Artik 305 Secure Board
ARH: ARMv7

### Tell us about your OS (Type & version):
Linux, Ubuntu 16.04
Linux artik 4.4.71-UNRELEASED #1 SMP PREEMPT Tue Aug 20 18:39:35 IST 2019 armv7l armv7l armv7l GNU/Linux

**Comment by kclchan** [comment]
Hi @sphapale, thanks for getting in touch with us.  Unfortunately, this is a known issue "Devices connected before the Bluetooth CA is initialized are ignored".  We have an internal ticket for this and will fix it in a future SDK release.  Thanks!

**Comment by mohitbansal19** [comment]
Hi @kclchan 

   Adding my observation in this issue that we found a workaround to resolve this issue. 
As there is a directive "ConnectByProfile" which came into the picture when phone connected to the bluetooth. The same directive came when we call "Alexa, connect my phone" after reboot. After this Alexa device connects to the previous attached phone. 

If we call the related API i.e "executeConnectByProfile" on Bluetooth init then we can auto-connect the device previously attached because Bluetooth::init will call after device reboot. 

Can you please check and let us know that how feasible this solution or workaround?
Below is the code snippet which we can change:- 
bool Bluetooth::init() {
    ACSDK_DEBUG5(LX(__func__));

    if (!m_db->open()) {
        ACSDK_INFO(LX("init").m("Couldn't open database.  Creating."));
        if (!m_db->createDatabase()) {
            ACSDK_ERROR(LX("initFailed").d("reason", "createDatabaseFailed"));
            return false;
        }
    }

    m_eventBus->addListener(
        {avsCommon::utils::bluetooth::BluetoothEventType::DEVICE_DISCOVERED,
         avsCommon::utils::bluetooth::BluetoothEventType::DEVICE_STATE_CHANGED,
         avsCommon::utils::bluetooth::BluetoothEventType::STREAMING_STATE_CHANGED},
        shared_from_this());

    m_mediaPlayer->setObserver(shared_from_this());

    executeUpdateContext();
    **executeConnectByProfile("A2DP-SOURCE", " ");   // Adding this API with A2DP-SOURCE**

    return true;
}

Thanks
Mohit Bansal

**Comment by mohitbansal19** [comment]
Hi @kclchan

Adding my observation in this issue that we found a workaround to resolve this issue.
As there is a directive "ConnectByProfile" which came into the picture when phone connected to the bluetooth. The same directive came when we call "Alexa, connect my phone" after reboot. After this Alexa device connects to the previous attached phone.

If we call the related API i.e "executeConnectByProfile" on Bluetooth init then we can auto-connect the device previously attached because Bluetooth::init will call after device reboot.

Can you please check and let us know that how feasible this solution or workaround?
Below is the code snippet which we can change:-

bool Bluetooth::init() {
ACSDK_DEBUG5(LX(func));

if (!m_db->open()) {
    ACSDK_INFO(LX("init").m("Couldn't open database.  Creating."));
    if (!m_db->createDatabase()) {
        ACSDK_ERROR(LX("initFailed").d("reason", "createDatabaseFailed"));
        return false;
    }
}

m_eventBus->addListener(
    {avsCommon::utils::bluetooth::BluetoothEventType::DEVICE_DISCOVERED,
     avsCommon::utils::bluetooth::BluetoothEventType::DEVICE_STATE_CHANGED,
     avsCommon::utils::bluetooth::BluetoothEventType::STREAMING_STATE_CHANGED},
    shared_from_this());

m_mediaPlayer->setObserver(shared_from_this());

executeUpdateContext();
**executeConnectByProfile("A2DP-SOURCE", " ");**   // Adding this API with A2DP-SOURCE

return true;
}

Thanks
Mohit Bansal

**Comment by caleighatamazon** [comment]
Hi there, sorry for our late response on this. Are you still having problems?

**Comment by ajaythakur-dev** [comment]
Replying on behalf of @mohitbansal19: Tested same on 1.18 issue still persists.
