### ISSUE TITLE
Alexa is streaming music after it is disconnected from internet

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1485]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
Alexa is streaming music after it is disconnected from internet

## Briefly summarize your issue:

While Alexa Playing music , if we disconnected the internet still it is playing music.
## What is the expected behavior?

It should stop playing music, if internet is disconnected.

## What behavior are you observing?

Alexa is playing music without internet also.

## Provide the steps to reproduce the issue, if applicable:

Alexa Play music
After it is streaming music, disconnect the wifi.

### What version of the AVS Device SDK are you using?
      <x.y.z>
AVS -1.10

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Android pie 

### Tell us about your OS (Type & version):
- [. ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Please find the link for reference.
https://drive.google.com/file/d/1maDDkjt70_gDYnhGkL0a6wuzPtbNK1Ng/view?usp=sharing

**Comment by kjkh** [comment]
Hi @dipalisb,

This is working by design. In order to provide a smooth playback experience despite varying network conditions, devices need to buffer audio data. What you are experiencing is the buffered audio data being played. After disconnecting the network, the buffered data will eventually drain, and playback should stop after some time. If you have further questions, please reopen the ticket and we will be happy to assist further.
