### ISSUE TITLE
[Memory profile] what is the minimum memory for running avs for a  long time

### ISSUE THREAD

**Issue by WksKing** [alexa/avs-device-sdk#1490]
Hi Amazon,
I'd like to have a long run test for avs function more than 8h, but it's always fails almost 6h.
here is my memory info:
```
# free -h
BusyBox v1.24.1 (2016-05-24 22:01:48 CST) multi-call binary.

Usage: free [-b/k/m/g]

Display the amount of free and used system memory
# free -b
             total       used       free     shared    buffers     cached
Mem:     161349632  139673600   21676032    1019904          0   54448128
-/+ buffers/cache:   85225472   76124160
Swap:            0          0          0
# 
```
does it enough for running avs long times? if not, can you provide a doc for describing the memory profile?
Thanks.

**Comment by mvelegon-amzn** [comment]
Hi @WksKing we currently do not have any such doc describing the memory profile. When you say it fails after 6h are you seeing the system run out of memory or is the sdk crashing for some other reason? Also, could you briefly explain what tests you are running so that we can get a better picture of the device's condition?
