### ISSUE TITLE
High quality tensorflow models for Alexa wake words

### ISSUE THREAD

**Issue by jonsmirl** [alexa/avs-device-sdk#1494]
The product I am designing uses a CPU that includes a hardware engine for running tensor flow models. I would like to use this engine for processing the wake word but I can not locate TF models for the Alexa hot words. This hardware engine is about 100x faster than doing wake word processing in code.

Can Amazon provide high quality (ie that can pass AVS certification) tensor flow models of the four Alexa wake words (Alexa, Compute, Echo, Amazon)?

**Comment by mvelegon-amzn** [comment]
Hi @jonsmirl thanks for reaching out.

Since the forum is meant for questions related to our code base, I don't think this is the right channel for this question. Could you try asking this question here: https://forums.developer.amazon.com/spaces/38/Alexa+Voice+Service.html some one from the AVS team could help you get the right answer. 

Thanks
