### ISSUE TITLE
Question: which script and where in main.cpp should be changed to control Microphone from command line?

### ISSUE THREAD

**Issue by rajdpandey** [alexa/avs-device-sdk#1500]
Hi,

I had asked a question earlier which was closed and dhpp told me that for the controlling of Microphone means turning it on and off from command line I had to change script and some changes in main.cpp.

I asked in thay issue but there was no reply so I am asking here: In which script and where & how should I do changes and in main.cpp also to control Microphone turning it on and off from command line in raspberry pi. 

As I have just learnt python and I am not familiar with C or C++  so I don't have any clue. I hope you all understand and help me regarding it..

Thanks.

**Comment by womw** [comment]
hi @rajdpandey 

previous issue in question: https://github.com/alexa/avs-device-sdk/issues/1499

You will need to update SampleApp/main.cpp to take in new args for enable/disable microphone. You will also need to update SampleApplication.cpp create() function to create without a microphone.

This implementation is outside of the scope of this forum and I will close the issue here. Feel free to re-open if you have more questions.
