### ISSUE TITLE
Skip limit test for IheartRadio

### ISSUE THREAD

**Issue by shikha-bansal** [alexa/avs-device-sdk#157]
The test document mentions that more than 6 Alexa skip commands to IHeartRadio should result in "TTS rendered stating the skip limit has been reached after 6 songs". 
I tried this with Alexa , play program A piece of work from IHeartRadio" . I was able to skip more than 7 times , no issues.

Please explain.

**Comment by sanjayrd** [comment]
Hi @shikha-bansal,

I think this has to do with the content that you're playing. When I try skipping, I reach the skip limit as expected. This might be because you're playing a program, which might not have a limit.

Can you try something else, i.e. playing Coldplay or the Beetles or something like that and seeing if you reach the skip limit?

Thanks,
Sanjay

**Comment by shikha-bansal** [comment]
Thanks Sanjay. Coldplay to rescue :)
