### ISSUE TITLE
Unable to generate the MVT report for Amazon Cloud and Amazon prime

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1622]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 We need to generate ALL PASS report for Amazon Cloud and Amazon prime music validation testing. We have used the check-list provided by Alexa Voice Service to test the scenarios. We are able to test but unable to generate report in MVT tool.

## What is the expected behavior?

--> Report should generate properly.
 
## What behavior are you observing?

--> We are unable to generate the report in **https://developer.amazon.com/alexa/console/avs/products/CDR8010/self-test?** for Amazon cloud and Amazon prime.

**Comment by scotthea-amazon** [comment]
Hello @dipalisb,

Where you able to generate reports for any other music service providers? What error message (if any) are you receiving?

Do you have an Amazon business contact for your device?  It so it may be helpful to work through them so you can share your product ID with them privately (vs publicly on this forum).

Best regards
-SWH

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity, but please open a new issue if you continue to have problems. However, as mentioned above, it will probably be most helpful for you to work with your Amazon business contact for this particular issue because then you'll be able to share your product ID privately with them (you should not share that information on our public Github forum).
