### ISSUE TITLE
Alexa completely not recognizing the command 'turn on loop mode'  under external music environment

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1635]
#908  Briefly summarize your issue:

## What is the expected behavior?
 Alexa should wake and answer "Loop mode on." When the song finishes, it automatically restarts.

## What behavior are you observing?
Alexa is waked but doesn't recognize the "turn on loop mode" utterance. We checked the History List, it shows that only part of the command is detected. Please check the below image for reference:
![loopMode_issue](https://user-images.githubusercontent.com/52921278/75899304-5fc7f500-5e61-11ea-8ea5-133ec83f9b73.png)

1) When we use the  command "Alexa turn on loop mode" 
2) Alexa is getting Wake but only half of the command is getting recorded by alexa.
i.e Alexa, turn on---is only stored in history list.
We have attached the logs 
[loop_issue.txt](https://github.com/alexa/avs-device-sdk/files/4287381/loop_issue.txt)
Please do analyze and share your observations. Please use the keyword: AlexaExeService for searching easily.
## Provide the steps to reproduce the issue, if applicable:
[Precondition]
1) Device is signed in to Alexa with an account that can play Amazon music.
2) Device is 0.9 meter far from the speaker and it's microphone is directly facing the speaker.
3) The utterance/command is played at 60~75 dbs.
[Steps]
1) Play the utterance "Alexa, play Happy by Pharrell Williams."
2) When Alexa is playing the song, play the utterance "Alexa, turn on loop mode."

## Tell us about your environment:
Hardware: DVR device
WWE version: Amazon PryonLite 1.13.4
### What version of the AVS Device SDK are you using?
AVS- SDK: 1.17.0

Please do help us to verify at your end and confirm whether this issue is SDK issue or not.

**Comment by mvelegon-amzn** [comment]
Hi @dipalisb thanks for reaching out. I am going to run some internal tests and get back to you on this.

**Comment by mvelegon-amzn** [comment]
We ran this test internally and we do not see any issues with "turn on looping" utterance. Could you please give more information to reproduce the issue? Also, please reach out to us through your Amazon Solutions partner as we will not be able to assist on Pryonlite issues on GitHub.

**Comment by DeepikaBalaga** [comment]
@mvelegon-amzn   @jpeddicord   @ArthurZey   @JamieMeyers   @dipalisb 

**Need to re-open this scenario as this issue is reproducible at our end.**
Below are the latest observations::
**[Precondition]**
1) Alexa log in with an JP account.
2) The distance between DUT and the speaker is 100 cm.
3) The speaker' volume is about 65~75 db.
4) Prepare the Japanese TTS voice of male/female.
Sample TTS website: https://ttsdemo.com/
Male voice: Kaito/Female voice: Hikari/Himari
**[Steps]**
1) Ask Alexa to play music 
    ("アレクサ、ファレルウィリアムスのハッピーをかけて")
2) Use male TTS voice to turn on loop mode.
    ("アレクサ、この曲をループモードでかけて")
3) Repeat 2) for 10 times.
4) Repeat 2) for 10 times with female TTS voice.

**ACTUAL RESULT:** ALEXA SONG IS NOT GOING TO LOOP MODE
Refernce table for actual result::  
<img width="477" alt="githubQuery" src="https://user-images.githubusercontent.com/31942830/78807974-6a3a5900-79e2-11ea-96a5-85ae2e6b3a5d.PNG">

**EXPECTED RESULT:** SONG MUST BE PLAYED IN LOOP MODE
**TEST ENVIRONMENT:**
Hardware: DVR device
WWE version: Amazon PryonLite 1.13.4
**What version of the AVS Device SDK are you using?**
AVS- SDK: 1.17.0

Please help to reproduce this issue at AMAZON end and share the observations/results.
