### ISSUE TITLE
Alexa Voice Service as Virtual Device Announcement Feature

### ISSUE THREAD

**Issue by ilkan** [alexa/avs-device-sdk#1636]
We want to allow users to use alexa's annoucement feature. At the below link end of the page I set the Announcements (Communications) enabled. But when I tried to 
We have a mobile app which has alexa voice service that user can send text/voice command to Alexa and get its response back. I've created a product(Application / Smart Home), then I set the Announcements (Communications) check box enabled at this link
https://developer.amazon.com/alexa/console/avs/products/<productName>/details/capabilities

However, when I tried to send command like "announce that dinner is ready" alexa response back to me "Sorry, You can't send announcements from this device yet." 

I thought we need to be certified partner to use it. I've tried this link under services tab https://developer.amazon.com/alexa/console/wwa/products/register/connection. But I couldnt find any option to select "Alexa Voice Service" option.

## What is the expected behavior?
Select, Alexa Voice Service for Registering Product https://developer.amazon.com/alexa/console/wwa/products/register/connection, then use Announcement Feature in a virtual Alexa Speaker.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X] Other - tell us more: Server Side App

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @ilkan thanks for reaching out, in order to use the announcements feature, the device has to go through a certification process. Please reach out to your AVS Solution Architect for more information on this. Thanks.

**Comment by ilkan** [comment]
> Hi @ilkan thanks for reaching out, in order to use the announcements feature, the device has to go through a certification process. Please reach out to your AVS Solution Architect for more information on this. Thanks.

We don't have any AVS Solution Architect. Where can I find? Is there any form for that? I filled [this ](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268)form. Noone replied me back.

**Comment by caleighatamazon** [comment]
You can ask questions about the certification process and AVS Solution Architects through the AVS Developer Console. Do the following:

1. Log in to the AVS Developer Console
2. Click on Support > "Contact support" for general assistance.
3. In the form, select Type: "Alexa Voice Service". Category: "Certification". Then fill out the remaining fields (Subject and Description) with information about your product and why you are seeking certification.

Our team (the SDK team) is not directly involved in certification -- we focus just on the SDK -- so I hope that by filling out this form, you'll be able to get more information about how to proceed with certification such that you are able to use the Announcements feature.

I hope this helps. I am going to close this issue since it is not an issue with the SDK, but rather that your product needs to go through the certification process.

Feel free to ask further questions about certification and being assigned an AVS Solution Architect at the community forums at AVS: https://forums.developer.amazon.com/spaces/38/index.html
