### ISSUE TITLE
Segmentation fault when reauth and then  m_messageSender->sendMessage(eventRequest);

### ISSUE THREAD

**Issue by kuodehai** [alexa/avs-device-sdk#1742]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Segmentation fault when   reauth   m_messageSender->sendMessage(eventRequest);

2136c:	91002260 	add	x0, x19, #0x8
[putty_avs_1.20.0_reauth1111_issue.log](https://github.com/alexa/avs-device-sdk/files/4822940/putty_avs_1.20.0_reauth1111_issue.log)

I have attached the DEBUG9 logs . please do refer & help us to analyze.
Thanks!
## What is the expected behavior?

reauth ,run normal.

## What behavior are you observing?

Segmentation fault when   reauth   m_messageSender->sendMessage(eventRequest);

## Provide the steps to reproduce the issue, if applicable:

auth success and then reauth  i->z->y

### What version of the AVS Device SDK are you using?
      <1.20.0. 1.19.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more:allwinner

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ *] Other - tell us more:openwrt

**Comment by caleighatamazon** [comment]
Hi there, thanks for reporting this. I was unable to reproduce it myself just now. Could you please attach DEBUG9 logs where you reproduce the problem? Also, can you reproduce this in 1.19.1 or 1.20, or both?

**Comment by kuodehai** [comment]
Hi  @caleighatamazon  putty_avs_1.20.0_reauth1111_issue.log  has attached DEBUG9 logs

**Comment by caleighatamazon** [comment]
Hi @kuodehai, those do not appear to be DEBUG9 logs for the SDK Sample App -- it's missing all the DEBUG9 logging. When DEBUG9 logs are enabled, you should see a lot of logs with this kind of format: `2020-06-23 05:24:46.367 [ 27] 9 HTTP2Transport:onActivity:this=0x7ff0cc3b5600` (for example).

But I don't see any DEBUG9 logs in the file you attached. 

It may be that you are not starting the Sample App correctly. It looks like this is the way you started the app:

```
SampleApp [J /etc/avs/AlexaClientSDKConfig.json   /etc/avs/  DEBUG9
```

I'm not sure what the `/etc/avs/` argument is for, since it doesn't look like your app has wakeword enabled (I don't see wakeword mentioned in the welcome menu).

**Comment by kuodehai** [comment]
Hi @caleighatamazon 
#1586 
issue 5: Segmentation err 2155c . step : i -> z ->Y reauth
putty_2020_0605_1441-reauth-SettingEventSender-sendEvent-SegmentationFault.log

**Comment by caleighatamazon** [comment]
Hi @kuodehai, unfortunately I still cannot see the debug logs in your latest response. It looks like that wasn't actually an attachment. I'll need the debug logs to look into this further. Thanks!

**Comment by kuodehai** [comment]
Hi @caleighatamazon
     reauth Failed_to_create_SampleApplication  and then restart SampleApp  i -> z-> Y  Segmentation fault.
[putty_avs_1.20.0_reauth_0628_11.log](https://github.com/alexa/avs-device-sdk/files/4841505/putty_avs_1.20.0_reauth_0628_11.log)

**Comment by mvelegon-amzn** [comment]
Hi @kuodehai thanks for sending the logs. We will get back to you on this shortly.

**Comment by mvelegon-amzn** [comment]
Hi @kuodehai I was not able to reproduce the issue following the same steps you mentioned. I also tried following the sequence multiple times i -> z -> Y but I couldn't see the same crash reported above.

In order to debug further could you please answer the following questions:

- Were there any changes made to the SDK when you ran this?
- Is the issue consistently reproducible?
- Please run the SampleApp with gdb and post the backtrace here where the error occurs. 


Note: To run SampleApp with GDB do the following:
In the build directory run this command: `gdb SampleApp/src/SampleApp`
then type in `r -C Integration/AlexaClientSDKConfig.json -L DEBUG9`
when the Segmentation Fault appears, type: `bt`

paste the output of the backtrace here.

**Comment by kuodehai** [comment]
Hi @mvelegon-amzn 
 1)only compile err  and then modify  NULL  to  (char*)NULL.
 2) now retry not reproducible

**Comment by mvelegon-amzn** [comment]
Hi @kuodehai Thanks for the additional information. I notice there is an issue in our code although its not causing a crash, it is something we will fix it in the next release.

It looks like the a new diagnostics object is not getting created after you request for reauthorization. In order to test this, could you please make this change in main.cpp and let us know if it fixes the issue you are seeing?

move lines 120 to 125 after line 127. In other words your change should look like this in main.cpp:


`
    std::unique_ptr<SampleApplication> sampleApplication;
    SampleAppReturnCode returnCode = SampleAppReturnCode::OK;

    do {
#ifdef DIAGNOSTICS
        std::unique_ptr<SDKDiagnostics> diagnostics = SDKDiagnostics::create();
        if (!diagnostics) {
            return SampleAppReturnCode::ERROR;
        }
#endif
        sampleApplication = SampleApplication::create(
            consoleReader,
            configFiles,
            pathToKWDInputFolder,
            logLevel
#ifdef DIAGNOSTICS
            ,
            std::move(diagnostics)
#endif

`

**Comment by kuodehai** [comment]
@mvelegon-amzn 
thanks for your reply.
