### ISSUE TITLE
Remove `.idea' from `.gitignore'

### ISSUE THREAD

**Issue by stefanofiorentino** [alexa/avs-device-sdk#1743]
`.gitignore' is overfitted on @bandkenamazoncom development requirements

Please, remove the `.idea' folder from the `.gitignore' file.

**Comment by caleighatamazon** [comment]
Hi @stefanofiorentino, if you're an Amazonian using the SDK, can you please reach out to the AVS SDK on-call directly (on Chime or Trouble Tickets)? I'll close this issue here and we can discuss further internally.

If I'm mistaken and you aren't an Amazonian, please open a new issue and we can keep chatting on Github.
