### ISSUE TITLE
How to get access token problem

### ISSUE THREAD

**Issue by ssalexa** [alexa/avs-device-sdk#1749]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Not sure whether it's an issue. 
I am going to retrieve m_accessToken from CBLAuthDelegate in debug mode. However, sometimes it shows the access token but sometimes not (It shows m_accessToken = ""). I know each CA/agent works on its own thread, so is it timing problem? Would you provide some suggestion? (I read the document and it mentions the access token is valid for one hour, so I assume I should receive it (same access token) all the time within one hour until it gets refreshed later, then new token should be shown.

## What is the expected behavior?
get access token, something like: "Atza|IwEBIH0ciXtEtlNrwEYb6CXAhOQUHZuGyZnhMrDha-R5IKKdD15NlCJHLTD7dJZn 
   888******************6qi6gtY_a3qGeyc9Xxpe7yWVl2Cbr7anPHss6cXhtbNR92bAHgB-MJn78H0X0Ba1bUR83ywDodV4wv8JCepspSiOhvQkA8JVPXiVP3_7i5ibnwywYKOjGGa0cQTCJ-MrrIwz5gbq9fnrSMMZ2X6NAx0EzuwdUCREG3NGFs5Ga9TfBcKyEcibfi-vQIRyfpvE9rjp9kaD6a8G5E9lnO3OGdwMZvoUF264KaCJLOU2D68bfiv57JPcpwbR1NVa4l8-**************"

## What behavior are you observing?
m_accessToken=""

## Provide the steps to reproduce the issue, if applicable:
Running app in debug mode multiple times

## Tell us about your environment:
Mac
### What version of the AVS Device SDK are you using?
      <1.20.0>

### Tell us what hardware you're using:
- [X ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [X ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @ssalexa Thanks for reaching out. Could you provide more information about how you are trying to access the authToken? Are you calling getAuthToken() method directly on CBLAuthDelegate? 

Since the auth token could be in a process of refreshing, you should make sure that you check for the current authorization state to see if its REFRESHED and then call the getAuthToken() method.

Here is an example in code on how to make sure you always get a valid authToken: 

https://github.com/alexa/avs-device-sdk/blob/master/CapabilitiesDelegate/src/DiscoveryEventSender.cpp#L133
