### ISSUE TITLE
How I do cross compile using cmake

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#179]
Hi avs team

How I do cross compile on openwrt platform.

**Comment by mradulan** [comment]
Hi sundq, as long as you can get all the [dependencies](https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#minimum-requirements-and-dependencies) on openwrt platform, you should be able to compile the SDK. The SDK works for Linux based systems, we have built and tested it on MacOS, Linux(Ubuntu) and raspbian. We have not tried compiling it for openwrt platform but since it is linux based, you should be able to build and run on it. Also what is the architecture you are working on? PowerPC or Arm-based?

**Comment by yxzb** [comment]
Dear mradulan，

Can i compile this SDK with ubuntu(x86)?

I compiled this SDK on Ubuntu (x86), and when I started AuthServer, it was always wrong.

The following error is reported：
--------------------------------------------------------------------------------------------------------

zhx@ubuntu:~/share/avs_sdk_linux/tempfile/mengmeng$ python AuthServer/AuthServer.py 
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
^Czhx@ubuntu:~/share/avs_sdk_linux/tempfile/mengmeng$

--------------------------------------------------------------------------------------------------------

I'm sure client data is right，I tried a lot ,but failed. Since you mentioned the architecture in this issue,so i wonder if SDK doesn't support Ubuntu (x86)?

Looking forward to your reply, thank you！

**Comment by mradulan** [comment]
Can you check in developer.amazon.com -> Security Profile -> Web Settings -> Allowed origin , Allowed return URL. Check if it is set to http://localhost:3000 and http://localhost:3000/authresponse

**Comment by mradulan** [comment]
SDK supports Ubuntu.

**Comment by yxzb** [comment]
Dear mradulan，
I set it just as you said，but report the same error.

Set as below
`
Allowed Origins | http://localhost:3000
-- | --
Allowed Return URLs | http://localhost:3000/authresponse
`
It reported the same error

`zhx@ubuntu:~/share/avs_sdk_linux/tempfile/mengmeng$ python AuthServer/AuthServer.py 
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
^Czhx@ubuntu:~/share/avs_sdk_linux/tempfile/mengmeng$ `

**Comment by rustihammer** [comment]
I had the same issue.  From what I see, Amazon doesn't allow http, it allows https only and I can only retrieve the refresh token if I use https as origin and return URL.  However the current AuthServer.py only support http.   I've to use other scripts from other avs projects to retrieve the refresh token and fill in the AlexaClientSDKConfig.json manually.

Can someone confirm this issue and fix the AuthServer.py to https?

**Comment by kclchan** [comment]
Hi @rustihammer and @sundq, 

Http can be used as the Allowed origin and Allowed return URL.  Can you try putting something in the deviceSerialNumber in AlexaClientSDKConfig.json and check again?

For example:
"deviceSerialNumber":"12345678"

Thanks,
Kenneth

**Comment by rustihammer** [comment]
Still no luck for me. I tried your suggestion but I couldn't get it right.  I even tried to modify the AuthServer.py to use https but it still return failed 400.  I tried another script using https but it was ok.  I guess it was something else causing the issue.

-----------------------------------------------------------------------------------------------
rustihammer@mba:~/BUILD$ python AuthServer/AuthServer.py 
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on https://127.0.0.1:3000/ (Press CTRL+C to quit)
127.0.0.1 - - [12/Oct/2017 00:44:20] "GET / HTTP/1.1" 302 -
-----------------------------------------------------------------------------------------------

AVS guys, I always want to say thank you for working hard on these project. Alexa is fun!

**Comment by BennyAvramson** [comment]
Hi @rustihammer,

Thanks!

Did you try opening the browser at [](http://localhost:3000) while the server is running?

Thanks,
Benny

**Comment by rustihammer** [comment]
Hi Bunny,

Sorry my issue was fixed at another thread, it was due to bad ProductID:
https://github.com/alexa/avs-device-sdk/issues/227

**Comment by thevamad** [comment]
@rustihammer : Do you have a makefile recipe for the AVS device sdk that you can share? Thanks!

**Comment by rustihammer** [comment]
@thevamad I cross compiled it for ARM, if that's what you're looking for:

This is my cmake command using the toolchain.cmake toolchain file.  Just FYI.  Need clean up for re-use:

```
$ cmake -DCMAKE_TOOLCHAIN_FILE=~/toolchain.cmake $SDK_SRC -DSENSORY_KEY_WORD_DETECTOR=OFF -DKITTAI_KEY_WORD_DETECTOR=ON \
    -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$LOCAL_BUILD_ARM/lib/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$LOCAL_BUILD_ARM/include \
    -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=$LOCAL_BUILD_ARM -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$LOCAL_BUILD_ARM/lib/libportaudio.a \
    -DPORTAUDIO_INCLUDE_DIR=$LOCAL_BUILD_ARM/include -DCMAKE_PREFIX_PATH=$LOCAL_BUILD_ARM -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD_ARM \
    -DCMAKE_BUILD_TYPE=DEBUG -Wno-dev
```

The  toolchain.cmake toolchain file for ARM

```
set(CMAKE_SYSTEM_NAME Linux)
set(TOOLCHAIN_PREFIX armv7-a)

set(TOOLCHAIN_PREFIX $ENV{SYSROOTS}/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-)

INCLUDE(CMakeForceCompiler)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)

set(CMAKE_SYSROOT $ENV{SYSROOTS}/cortexa7hf-neon-poky-linux-gnueabi)
set(CMAKE_PREFIX_PATH ${CMAKE_SYSROOT}/usr/lib/cmake)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(COMPILER_FLAGS " -march=armv7ve -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${COMPILER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMPILER_FLAGS}" CACHE STRING "" FORCE)
```

which makes uses of environments variables which I exports below:

```
    export SOURCE_FOLDER_ARM=$HOME/avs-deps-arm
    export LOCAL_BUILD_ARM=$HOME/local-builds-arm
    export LD_LIBRARY_PATH=$LOCAL_BUILD_ARM/lib:$LD_LIBRARY_PATH:/usr/lib/:/opt/fsl-imx-x11/4.1.15-2.1.0/sysroots/cortexa7hf-neon-poky-linux-gnueabi/lib/
    export SDK_SRC=${HOME}/avs-device-sdk
    export SYSROOTS=/opt/fsl-imx-x11/4.1.15-2.1.0/sysroots
    export SYSROOT=/opt/fsl-imx-x11/4.1.15-2.1.0/sysroots
    export CMAKE_SYSROOT=$SYSROOT

    ### ENABLE for CROSS COMPILE avs-device-sdk!!!
    export PKG_CONFIG_DIR=
    export PKG_CONFIG_LIBDIR=${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig
    export PKG_CONFIG_SYSROOT_DIR=${SYSROOT}
    export PKG_CONFIG_PATH=${SYSROOT}/usr/lib/pkgconfig
```

**Comment by HavensTian** [comment]
hi @rustihammer ,do you work out this issue? I cross compile it on MIPS platform now，has any suggestions?
much thanks!

**Comment by avp24** [comment]
Hi @rustihammer Thank You for providing such information. With the help of your toolchain file and cmake command I am able to initiate corss compilation process of avs sdk for ARM but I get stuck later on when it tries to compile Kitt ai. Initially i was getting errors of cannot find -lblas. Below mentioned procedure was followed to resolve this error:
1. As I was not able to cross compile blas for ARM so using using yocto and bb file from openembedded I compiled blas for ARM.  Did you cross compile blas for ARM? Do you have any suggestions on this?
2. In CMakeLists.txt i replaced blas to openblas. Again configuring and compiling now throws me error in code.
For ref:
[ 93%] Built target CapabilitiesDelegateTest
[ 93%] Building CXX object CapabilityAgents/Alerts/test/CMakeFiles/ReminderAlertTest.dir/ReminderAlertTest.cpp.obj
../src/libKITTAI.a(KittAiKeyWordDetector.cpp.obj): In function `alexaClientSDK::kwd::KittAiKeyWordDetector::KittAiKeyWordDetector(std::shared_ptr<alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits> >, alexaClientSDK::avsCommon::utils::AudioFormat, std::unordered_set<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::KeyWordObserverInterface>, std::hash<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::KeyWordObserverInterface> >, std::equal_to<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::KeyWordObserverInterface> >, std::allocator<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::KeyWordObserverInterface> > >, std::unordered_set<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::KeyWordDetectorStateObserverInterface>, std::hash<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::KeyWordDetectorStateObserverInterface> >, std::equal_to<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::KeyWordDetectorStateObserverInterface> >, std::allocator<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::KeyWordDetectorStateObserverInterface> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<alexaClientSDK::kwd::KittAiKeyWordDetector::KittAiConfiguration, std::allocator<alexaClientSDK::kwd::KittAiKeyWordDetector::KittAiConfiguration> >, float, bool, std::chrono::duration<long, std::ratio<1l, 1000l> >)':
/home/ap/Desktop/VVDN_AVS/alexa/avs-device-sdk/KWD/KittAi/src/KittAiKeyWordDetector.cpp:136: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../src/libKITTAI.a(KittAiKeyWordDetector.cpp.obj): In function `std::unique_ptr<snowboy::SnowboyDetect, std::default_delete<snowboy::SnowboyDetect> > alexaClientSDK::avsCommon::utils::memory::make_unique<snowboy::SnowboyDetect, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
/home/ap/Desktop/VVDN_AVS/alexa/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Memory/Memory.h:35: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/build.make:100: recipe for target 'KWD/KittAi/test/KittAiKeyWordDetectorTest' failed
make[2]: *** [KWD/KittAi/test/KittAiKeyWordDetectorTest] Error 1
CMakeFiles/Makefile2:4678: recipe for target 'KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all' failed
make[1]: *** [KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Any suggestions to solve this error?
Thanks!

**Comment by avp24** [comment]
@rustihammer On executing SampleApp on ARM platform I get below error:
(SampleApp:25804): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:25804): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
1970-01-02 02:24:53.847 [  1] C SampleApplication:Failed to create media player for speech!
1970-01-02 02:24:53.847 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

How to solve this error?
Thanks!
