### ISSUE TITLE
EndpointId in Alarms API

### ISSUE THREAD

**Issue by debugguru** [alexa/avs-device-sdk#1832]
## Briefly summarize your issue:
Error while calling Alarms API 

## What is the expected behavior?
I should be able to call the alarm API and set the Alarm

## What behavior are you observing?

Getting an error INVALID_ENDPOINT_ID_FORMAT

## Provide the steps to reproduce the issue, if applicable:

Call the create Alert API using Postman and authorisation token in header

### What version of the AVS Device SDK are you using?
Call API using POSTMAN
Request and response documented here https://forums.developer.amazon.com/questions/233700/endpointid-in-alarms-api.html
I am generating the toke using ask cli
ask util generate-lwa-tokens

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @debugguru, this Github forum is only for issues related to the AVS Device SDK. It looks like your question is about using the Alerts API with Postman. Seeing as you're not using the SDK, unfortunately we are not able to support you at this forum.

Please head on over to the Amazon Developer Help Forums and related support documentation here: https://developer.amazon.com/support/

I'm closing this issue here since it's unrelated to the SDK.

If I've misunderstood and you _are_ using the SDK, feel free to open a new issue with us with additional details.

**Comment by debugguru** [comment]
Thanks @caleighatamazon . I had same thoughts as you but I was directed to ask question here by the Solution Architect team at AWS. As you can see I have already raised question in AWS forum https://forums.developer.amazon.com/questions/233700/endpointid-in-alarms-api.html and the response there was to raise a question here. Feels like I am going in circle. Could you please suggest where I can raise this issue?

**Comment by caleighatamazon** [comment]
Hi @debugguru , that does sound frustrating! I saw your response to the SA on the developer forums, and I think that was the right thing for you to do. Hopefully they will take a second read of the issue and be able to help you further. As I said, you are not using the AVS Device SDK, so our forum here isn't the right place to get support -- all of us over here only work on the AVS Device SDK.

Feel free to comment here again if the SA on that forum disagrees with our assessment. Or you could start a new issue on that forum if they don't respond to your comment (sometimes comments get lost in the shuffle).
