### ISSUE TITLE
Playback router pause stops rather than pausing

### ISSUE THREAD

**Issue by Mechan0** [alexa/avs-device-sdk#1896]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What is the expected behavior?

It seems that this is intended behaviour, as the tests indicate but it seems odd that the existing `PlayerActivity::PAUSED` is not issued instead. Our application needs to know what the playback could be resumed and is not stopped to show/hide audio controls, so the audio player observer issuing a `PlayerActivity::STOPPED` would indicate that the source has been disposed of.

```C++
TEST_F(AudioPlayerTest, test_localPause) {
    sendPlayDirective();

    EXPECT_CALL(*(m_mockMediaPlayer.get()), stop(_, _)).Times(AtLeast(1));

    ASSERT_TRUE(m_audioPlayer->localOperation(LocalPlaybackHandlerInterface::PlaybackOperation::PAUSE_PLAYBACK));
    ASSERT_TRUE(m_testAudioPlayerObserver->waitFor(PlayerActivity::STOPPED, MY_WAIT_TIMEOUT));
}
```

## What behavior are you observing?

We have a custom media player implementation. Instead of it receiving a pause directive, it instead receives a stop directive when either a local operation or button press is issued to the playback router, making it unresumable. For a long running source (E.X "Tell me a story"), interrupting it with a "tell me a joke" results in the "Tell me a story" pausing, then resuming afterwards. Presumably this means that this functionality should work through the playback router, but none of the media players ever receive a pause directive when the pause button press is issued.

## Provide the steps to reproduce the issue, if applicable:

1. start playback of a long running audio source, such as "Tell me a story".
2. Issue a pause command:
```C++
m_defaultClient -> getPlaybackRouter() -> localOperation(avsCommon::avs::LocalPlaybackHandlerInterface::PlaybackOperation::PAUSE_PLAYBACK);
```
3. `AudioPlayer` will be `STOPPED` *not* `PAUSED`
## Tell us about your environment:

Custom media player implementations, using default client's playback router.
### What version of the AVS Device SDK are you using?
      1.2.2.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
iOS 

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
HI @Mechan0, please note that pause state in AudioPlayer is mostly used only for interruptions (e.g. barge-in).  The AudioPlayer AVS API (https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/audioplayer.html) has only the STOP and PLAY directive for pause and resume.  To pause, AVS sends to the device a STOP directive.  To resume, AVS sends a PLAY directive with the appropriate offsetInMilliseconds.  And for these reasons, that's why a PAUSE localOperation is mapped to STOP in AudioPlayer.

**Comment by Mechan0** [comment]
@kclchan Thank you for the reply! This is rather confusing so glad to have a definitive reason. So in our case, what would you suggest to determine the difference between a stop directive returning due to a pause command, in which case we need to persist showing our playback controls to the user, or an error that results in a stop. Even setting a variable on our side after any mechanism issues a local stop and waiting for the audio player to issue a PlayerActivity::Stopped, it seems possible that a race condition could occur. Suppose a local stop is issued, yet instead of the stop being returned due to the pause command being issued, it's instead issued some other reason (such as an error) that then makes it unplayable and so the "play" control would then do nothing when pressed.

**Comment by caleighatamazon** [comment]
Hi @Mechan0 , AudioPlayer doesn't have a single, easy way to signal an error to a listener. I'll note this as a feature request.

But there are a few workarounds to be notified of errors, that might work for you:

- MessageSenderInterface will be used to send a PlaybackError to AVS, so you could monitor for that to know if there's an error.
- The 'Play' command can fail (and will, for several reasons, including the pipeline being shutdown, which will happen for an error).
- The Stop command can also fail, and will if the player is already stopped
- You could even add your own MediaPlayerInterface listeners to the AudioPlayer media players before you pass those media players to the CA. Then you could also monitor those media players (since an error could happen there, too).
