### ISSUE TITLE
Audio file input to AVS using AUDIO INJECTION parameter not working

### ISSUE THREAD

**Issue by mkb878** [alexa/avs-device-sdk#1920]
## Briefly summarize your issue:

I am trying to inject an audio file to the AVS after building the sample app with audio injection enabled (-DAUDIO_INJECTION=ON). I can reach the Audio Injection screen and input a .wav file generated according to the specifications for audio file input, but then there is no response from the AVS. The voice history for the device does not indicate that any input has been received. I am grateful for any suggestions on what the issue might be. 

## What is the expected behavior?

Audio output and/or terminal print-out from the AVS in response to the audio file injection (the .wav file contains synthesised speech for 'what is the time')

## What behavior are you observing?

This is the output to terminal following audio file injection (running the sample app with DEBUG9):

1
/home/mkb/TTS_library/Audios/whatTime.wav
2021-04-29 16:07:10.376 [  1] 9 ThreadPool:obtainWorker:created=26,obtained=31,releasedToPool=25,releasedFromPool=6,outstanding=0
2021-04-29 16:07:10.376 [  c] 9 TaskThread:startThread:moniker=  c,duration=132
2021-04-29 16:07:10.376 [  c] 5 SDKDiagnostics:getAudioInjector
2021-04-29 16:07:10.376 [  c] 5 FileBasedAudioInjector:injectAudio
2021-04-29 16:07:10.376 [  c] 5 AudioInjectorMicrophone:injectAudio

After this the app just hangs. 

## Tell us about your environment / hardware / OS:

I am running the AVS on a Ubuntu virtual machine (18.04), using VirtualBox on a Windows host. 
These are the details of the .wav file I am injecting:

whatTime.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz

**Comment by caleighatamazon** [comment]
Hi there, thanks for reporting this. Can you answer a few more questions to help us debug?
1. If you press "q" to exit the app while it's hanging, what happens?
2. How did you build the Sample App? What cmake flags? Did you use our script?
3. Can you please attach full logs? (As an attachment, please don't copy and paste them here.)
4. Is it possible for you to also attach the wav file here, as well?

**Comment by mkb878** [comment]
Hi,
Thank you for the reply. In answer to your questions:

1. When I press q while the app is hanging, it exits the Audio Injection screen and returns to the Diagnostics options page.
2. I built the sample app for audio injection with the following cmake parameters: 
`cmake $HOME/[folder name]/source/avs-device-sdk -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=OFF -DDIAGNOSTICS=ON -DAUDIO_INJECTION=ON -DCMAKE_BUILD_TYPE=DEBUG ` (I previously built it with PortAudio enabled, and it worked fine with voice input via pressing 'h' )
3. Print-out of logs from the terminal attached.
4. The .wav file is attached (in a zip file).

Thank you for any help.


[whatTime.zip](https://github.com/alexa/avs-device-sdk/files/6420102/whatTime.zip)
[AVSlog_audioinject.txt](https://github.com/alexa/avs-device-sdk/files/6420115/AVSlog_audioinject.txt)

**Comment by caleighatamazon** [comment]
Hi @mkb878 , thanks for providing more detail. The issue here is that because you've built the SDK without wakeword enabled, you have to press "t" then inject audio in order for the SDK to actually process the audio. When wakeword is disabled, the SDK will only process audio if the user presses "t" or "h" first. Audio injection is a simple microphone replacement. Your PortAudio example worked because you pressed "h" first.

This can be inconvenient for manually testing with audio injection when wakeword is disabled, since you have to (1) press "t" or "h" and then (2) navigate to the audio injection menu before the "Listening..." state times out. Sometimes it can be hard to do that quickly. If you find that difficult to do, you can do is modify the Sample App such that the audio injection option is closer to the top menu. You'll want to take at `SampleApp/src/UserInputManager.cpp` and add a new menu option that lets you directly inject audio from the top-level menu.

Hope this helps.

**Comment by mkb878** [comment]
Hi
Thank you for this advice - I made some modifications to UserInputManager.cpp as suggested, and the audio injection is working now.
