### ISSUE TITLE
Token handling with companion app example

### ISSUE THREAD

**Issue by albanoandrea** [alexa/avs-device-sdk#1961]
## Briefly summarize your issue:
We have an AVS implementation that will work with a companion App for authorization process.
We have done both app LWA implementation and Bluetooth communication.

What is not clear now is how to modifiy AVS client side to make it work correctly and not to break anything.

We have understood the explanation [here](https://developer.amazon.com/it-IT/docs/alexa/alexa-voice-service/authorize-companion-app.html), but it's not clear in the client how to remove the CBL part and substitute it with the LWA token refresh procedure.

There is no sample to start from?

### What version of the AVS Device SDK are you using?
     1.23.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: Custom HW based on Linux/Cortex-A

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi,

In order to use your own authorization mechanism, you can directly implement [AuthDelegateInterface](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/AuthDelegateInterface.h) if using SDK versions older than 1.25.0. For 1.25.0+, there is a new interface, [AuthorizationAdapterInterface](https://github.com/alexa/avs-device-sdk/blob/master/core/Authorization/acsdkAuthorizationInterfaces/include/acsdkAuthorizationInterfaces/AuthorizationAdapterInterface.h) that is available.

These interfaces will allow you to pass the LWA access token that the rest of the SDK requires in order to communicate with AVS.

**Comment by kjkh** [comment]
Thank you for your suggestion. I have created a feature request for supporting authorization via the CompanionApp.

I have some comments that can hopefully help with your custom token implementation.

The CBLAuthDelegate implementation is specifically designed to only use the CBL method. Unfortunately, it was not intended to support other methods. Instead of modifying CBLAuthDelegate, directly implementing the AuthDelegateInterface and passing that into DefaultClient may be a cleaner solution.

DeviceInfo does expose a create method which allows you to instantiate from parameters rather than a ConfigurationNode object. From your description, would it be possible to delay SDK initialization until the CompanionApp initiates an authorization or pair request?

I would also discourage using an arbitrary value for endpointId creation. Doing so is not within spec, and could result in undefined behavior.

**Comment by blazusiak-amazon** [comment]
Due to over 2 months of inactivity from the original requester, this issue will be closed. If the requester feels that the issue has not been fully resolved and still requires support they may submit a new issue.

**Comment by Kiennguyen08** [comment]
Hi @albanoandrea can you tell me how you transmit information get from companion app to device?
