### ISSUE TITLE
I've run a custom skill, but it's said that this feature is only available on certified Alexa-powered devices.

### ISSUE THREAD

**Issue by hatosan0112** [alexa/avs-device-sdk#2002]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Running custom skills, this feature is only available on certified Alexa-equipped devices

## What is the expected behavior?

Custom skills work the same as on the Alexa Skill Kit

## What behavior are you observing?

This feature is said to be available only on certified Alexa-equipped devices

## Provide the steps to reproduce the issue, if applicable:

After installing Alexa on Jetson and creating a custom skill with the Alexa Skill Kit, launch AlexaSampleApp from Jetson to call the custom skill.

### What version of the AVS Device SDK are you using?
      latest version

### Tell us what hardware you're using:
Jetson Xavier NX

### Tell us about your OS (Type & version):
Ubuntu18.04

**Comment by blazusiak-amazon** [comment]
Hello @hatosan0112, 
This behavior is due to the fact that your device is uncertified; only limited features are available for uncertified devices: https://github.com/alexa/avs-device-sdk/security/policy . Once you have certified your device, it should work as expected. You can find out more about device certification here: https://developer.amazon.com/en-US/alexa/devices/connected-devices/business-resources/works-with-alexa
