### ISSUE TITLE
AVS Device SDK Integration in iOS Application

### ISSUE THREAD

**Issue by MansoorZ** [alexa/avs-device-sdk#2062]
Hi Team,

    I would like to integrate Alexa Voice Service in to my application, through that I need to control my Alexa supported devices Such as light, plug and other home appliances.

I have integrated LWA SDK in my iOS application for authorisation and got successfully logged in, I have used my amazon account for login which is already registered in ALEXA amazon app as well. Registered my Alexa supported devices to the same account.

These all, LWA SDK and AVS API coding has been done from my stand alone iOS application which means integrated the voice service in to my own application and trying to control the device from the same application, when I say Alexa turn on my device, it is not working and Alexa replying as"That feature only available in certified built in devices".\

I am not able to sort out this issue, please help me to control the Alexa supported device from standalone application.

Created the product in AVS dashboard and used the API key and product ID in my code base,

Development Language is Swift iOS.

Device - iPhone, OS version - iOS 16.0

Awaiting for your reply.

Thanks
Mansoor

**Comment by kclchan** [comment]
Hi @MansoorZ, this behavior is due to the fact that your device is uncertified; only limited features are available for uncertified devices: https://github.com/alexa/avs-device-sdk/security/policy . Once you have certified your device, it should work as expected. You can find out more about device certification here: https://developer.amazon.com/en-US/alexa/devices/connected-devices/business-resources/works-with-alexa
