### ISSUE TITLE
How can  i create a executable file of SampleApp  

### ISSUE THREAD

**Issue by snailwft** [alexa/avs-device-sdk#215]
Hi,
I create a build directory, and after i run cmake、make.  I navigate to the SampleApp/src folder from my build directory,but i can't find  the executable file of SampleApp. Please help me, Thanks a lot.

**Comment by Longynus83** [comment]
Hi snailwft, 
In order to get the SampleApp executable under that folder you need to properly configure the CMake command line resolving both the PortAudio and GStreamer dependencies.
These dependencies are mandatory, as the SampleApp Cmake file will check for both of these to be matched and, in case it is unable to find them, it will silently skip the SampleApp build process, as per following extract from the CMake file:

`if(PORTAUDIO AND GSTREAMER_MEDIA_PLAYER)
add_subdirectory("src")
endif()`

Did you already set the command line to provide those inputs?

**Comment by snailwft** [comment]
Hi,@Longynus83
Oh, I didn't do that.  I try it,Thank you very much.

**Comment by dhpp** [comment]
Thanks both - closing this issue - please re-open if the problem persists.
