### ISSUE TITLE
When i execute TZ=UTC make all integration, the following error occurred

### ISSUE THREAD

**Issue by snailwft** [alexa/avs-device-sdk#216]
Hi,
2017-10-09 03:15:23.802 [  1] I DirectiveRouter:onDeregisteredCalled:handler=0x90d0d68
[       OK ] AudioInputProcessorTest.audioWithoutAnyTrigger (7065 ms)
[----------] 13 tests from AudioInputProcessorTest (247154 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 1 test case ran. (247154 ms total)
[  PASSED  ] 12 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AudioInputProcessorTest.tapToTalkMultiturn

**Comment by dhpp** [comment]
Hi snailwft,

I'd like to ask a few things - firstly, does this replicate consistently?

If it does, could you please provide us with more logs, so we can help debug the issue?  To do this, you'll need to compile the code so that logging is enabled (via  -DCMAKE_BUILD_TYPE=Debug in the CMake file), and run that particular integration test manually (directly executing it from the Integration/test directory).

Thanks,

-David

**Comment by scotthea-amazon** [comment]
Hi snailwft,

There has been no reply to the last question posted on this issue, and it has been a long time.  So, I am losing this issue.  Please re-open this issue if I have closed it in error.

Thank you,
-SWH
