### ISSUE TITLE
Can I use sample app normally without build with a Wake Word Detector?

### ISSUE THREAD

**Issue by snailwft** [alexa/avs-device-sdk#223]
hi,
Because my system is ubuntu, I look at the wake word detection in the wiki and do not support the ubuntu x86 platform, but I don't want to buy it  from Sensory Sales now.

**Comment by dhpp** [comment]
Hi snailwft,

Yes this is fine - you can interact with the SampleApp via keyboard interaction (where you press 't' to invoke Alexa listening to you instead of wake-word).

Since you don't have wake-word detection libraries on your system, just ensure you run cmake without specifying any of the wake-word flags, which are AMAZON_KEY_WORD_DETECTOR, KITTAI_KEY_WORD_DETECTOR, SENSORY_KEY_WORD_DETECTOR.  In this case, you'll get a non-wake-word build.

Any other questions, please let us know, thanks.
-David
