### ISSUE TITLE
Run AuthServer failed

### ISSUE THREAD

**Issue by yxzb** [alexa/avs-device-sdk#227]
Hi,

when i try to run the AuthServer,it failed and reported as below:

`The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
`

and then login 'http://127.0.0.1:3000/ ',the website reported that:

`We're sorry!
An error occurred when we tried to process your request. Rest assured,we're already working on the problem and expect to resolve it shortly`

How can i solve this problem?

**Comment by sdumorti** [comment]
Hi,

Even though the wiki says about **AlexaClientSDKConfig.json**:
>...deviceSerialNumber isn't strictly required...

I had to put something (e.g. 1) otherwise I had the same error you mentioned.

**Comment by yxzb** [comment]
Hi sdumorti,

this is code:

`{
    "authDelegate":{
        "clientSecret":"xxx",
        "deviceSerialNumber":"12345678",
        "refreshToken":"",
        "clientId":"xxx",
        "productId":"raspberry"
     },

   "alertsCapabilityAgent":{
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/alerts.db",
        "alarmSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01._TTH_.mp3",
        "alarmShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01_short._TTH_.wav",
        "timerSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02._TTH_.mp3",
        "timerShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02_short._TTH_.wav"
   },

   "settings":{
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/settings.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
          }
    },

   "certifiedSender":{ 
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/certifiedSender.db"
    }
 }
`

so i have put the string "12345678",but i still have the same problem

**Comment by sdumorti** [comment]
Hi yxzb,

If the error message shows up before you have a chance to enter your Amazon credentials on the http://localhost:3000 page, you might have not entered the proper _Allowed origins_ and _Allowed return URLs_ on your developer account.
Check these URLs in the security profile associated to your device on your developer account.
It can also be an issue with the _productId_, check that it matches exactly the _Product ID_ of your your device on your developer account.
Sames goes for _clientSecret_ and _clientId_

**Comment by rustihammer** [comment]
ok I can successfully get the refresh token using AuthServer now, thanks to sdumorti's hint. Let me share my experience.

I was copying the AlexaClientSDKConfig.json config from raspberrypi's quick start guide(https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide), which use
"deviceTypeId":""
instead of
"productid"
in the AlexaClientSDKConfig.json, thus got the 400 error. Continue with the URL amazon developer login will give me another error.

Note that the productid is not shown on amazon developer's security profile page.  It's actually in the product information page.  Fix that then my authentication was done successfully.

Now I still got the request failed with error code 400 response.  However, continue to open the page http://127.0.0.1:3000/ at my browser, it will login to the amazon developer page and get the fresh token updated to the json file successfully.  I tried http and https and both work.

Here is my log:
`
rustihammer@mba:~/BUILD_KITTAI$ python AuthServer/AuthServer.py 
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
127.0.0.1 - - [13/Oct/2017 01:07:27] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [13/Oct/2017 01:07:34] "GET /authresponse?code=ANxfKCXDFXpLnFtAAsvF&scope=alexa%3Aall HTTP/1.1" 200 -
rustihammer@mba:~/BUILD_KITTAI$
`

**Comment by yxzb** [comment]
Hi sdumorti,rustihammer,

Thank you very much,I solved my problem, according to your tips.

My mistake lies in the wrong ProductID.

A few days ago there's nowhere to find the deviceTypeId,so I just put "raspberry" instead and forgot to change the ProductID  later.
