### ISSUE TITLE
what about get access token use other way?

### ISSUE THREAD

**Issue by snailwft** [alexa/avs-device-sdk#266]
hi,
Viki says Authserver can only be used for testing. The product must be commercialized in other ways to obtain access token. If other methods, sample app code needs to be changed?What about the changes?
Get the access token use other method is still fill in AlexaClientSDKConfig. Json of the reflesh token field?

**Comment by bandkenamazoncom** [comment]
I don't understand the issue here.  Please rephrase the question.

**Comment by ryan-esty** [comment]
@snailwft is this similar to #263? If you are asking how would you get the authorization token into your json file after deployment I would follow this link https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-site.html mentioned in #263. I believe the AuthServer is using the "Authorization Code Grant" method. Basically you need to have a website where your product can get that token after the user logs in. The other method can be done on the client but you need to manage the token since it expires.

**Comment by snailwft** [comment]
hi, @ryan-esty,
Thank you very much for your help .

**Comment by bandkenamazoncom** [comment]
This sounds resolved.   Closing for now, if it's not sufficient, please re-open.
