### ISSUE TITLE
About the site of avs server.

### ISSUE THREAD

**Issue by NyxRockchip2017** [alexa/avs-device-sdk#302]
When I test the device,I found the site "https://avs-alexa-eu.amazon.com" is better to connect and reponse than "https://avs-alexa-us.amazon.com".

Is it reason that I test it in china ?

**Comment by frozenberg** [comment]
Hi @NyxRockchip2017, what do you mean by "better to connect"?

**Comment by anu-mathur** [comment]
Hi @NyxRockchip2017 
I am doing a user study on the AVS-device-SDK and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tiny.amazon.com/m48sz8fg/AVS-ContactForm) and I will get in touch with you.
Thanks

**Comment by sanjayrd** [comment]
Hi @NyxRockchip2017,

This might be due to geographic location. This [link](https://developer.amazon.com/docs/alexa-voice-service/api-overview.html#endpoints) gives you the possible endpoints. Note that there is a new Asian region endpoint that may be better since you're located in China.

Thanks,
Sanjay
