### ISSUE TITLE
can't play TuneIn

### ISSUE THREAD

**Issue by cuizhenke** [alexa/avs-device-sdk#324]
Hi AVS team,
    We are using SDK 1.2 to test music playing.Our device can't play TuneIn.Please help me check,Do our system missing something?For more log,,please see log file.
[TuneIn log.txt](https://github.com/alexa/avs-device-sdk/files/1460271/TuneIn.log.txt)
thanks.
17-11-10 03:42:49.850 [ 2b] E PlaylistParser:noChildrenURLs
2017-11-10 03:42:49.850 [ 2b] E UrlSource:parseError
2017-11-10 03:42:49.851 [  8] E UrlSource:preprocess:reason=noValidUrls
2017-11-10 03:42:49.851 [  2] 0 MediaPlayer:handlePlayCalled:idPassed=2,currentId=2
2017-11-10 03:42:49.853 [  2] 0 MediaPlayer:handlePlay:attemptBuffering=0
2017-11-10 03:42:50.211 [  2] 0 MediaPlayer:handlePlay:startingState=PLAYING,stateReturn=FAILURE
2017-11-10 03:42:50.211 [  2] E MediaPlayer:handlePlayFailed:reason=gstElementSetStateFailure

**Comment by jjamazon** [comment]
Hi cuizhenke,

What station were you playing ? How can we reproduce this ?

**Comment by cuizhenke** [comment]
Hi @jjamazon :
just ask Alexa, play C89.5 on TuneIn.Is it because I can't access the web site?

**Comment by kencecka** [comment]
Hi @cuizhenke,

Sorry for the slow response on this.  I tried asking Alexa to "play C89.5 on TuneIn", but she couldn't find that station.  In general, and from your log, I would guess that there is a problem with the specific station you are asking for.  You might try a different station (for example, I just tried "play KUOW on TuneIn" and it worked fine) to see if you have a general problem with TuneIn, or just with that specific "C89.5" station.

Ken

**Comment by sanjayrd** [comment]
Hi @cuizhenke,

I just tried reproducing the step you asked for and it worked fine for me (OS: Mac, SDK Version 1.3). Could you try upgrading and seeing if you still have the issue? 

Also, the following log message:
`
17-11-10 03:42:49.850 [ 2b] E PlaylistParser:noChildrenURLs
`
indicates to me either a parsing error in the playlist parsing step locally, or a malformed playlist on the server end.

Closing for now since due to inactivity, but please reopen if you're still seeing this issue.

Thanks,
Sanjay
