### ISSUE TITLE
Cannot build SampleApp on Mac for i386 architecture

### ISSUE THREAD

**Issue by scurdy** [alexa/avs-device-sdk#353]
## What version of the AVS Device SDK are you using?
master v1.2.1
      
## Briefly summarize your issue:
I would need to be able to build SampleApp for 32 bits architecture. The multiple dependencies , e.g. curl, gstreamer, portaudio etc..., prevent me from building it. I need to mention that I also made some code change to be able to serve my purpose so a binary from Amazon would not be able to help.

## What behavior are you observing?
during linking compiler returns an error due dependencies built for 64 bits platform.

## Provide the steps to reproduce the issue, if applicable:
change cmake setup with build_architecture i386, re-configure and re-generate
make SampleApp -j8

## Tell us about your environment:
I am using an application called max MSP. Max MSP is used in a context of a real-time signal processing framework for development and tuning purpose. There exists a lot of build-in objects but it also offers the possibilities to build a so called "external". This is a kind of C wrapper around some your own code in order to make a custom object that canm be integrated into the framework. In my case the real-time pipeline involved, has a as WWD end-point algo that triggers the Alexa ASV. I took Alexa SDK, made some code change and wrap it into one of those "external".
Our application needs to run @16kHz sampling rate and Max offers some audio drivers that unfortunately crashes when Max environment runs in 64 bits mode. Hence the need to be able to build Alexa sampleApp in 32 bits.

### Tell us what hardware you're using:
MacBook Pro (Retina, 15-inch, Mid 2015)
v10.13.1

**Comment by kencecka** [comment]
Hi @scurdy,

The SDK and SampleApp work fine with 32-bit architectures.  We regularly validate this when we build for Raspberry Pi.  But it's easier there, where the system is already 32-bit, so all the dependencies are already available in 32-bit flavors.

To build a 32-bit version of the SDK on a Mac, which is natively 64-bit, you will need to first provide 32-bit versions of all of the dependencies.  By default, you are probably trying to build/link against the 64-bit versions of the dependencies, which is not going to work.

You've noted the dependencies above.  You'll need to go through each of them, review how you installed them, and then determine how to install a 32-bit version.  This may require building from source, or it may be something you can do with an extra parameter to a package manager (such as homebrew or macports).  Once you have 32-bit versions installed, you may need to pass some additional flags or environment variables to the SDK cmake command to ensure it is seeing your 32-bit versions instead of the 64-bit versions.

Once you dig into this a little more, if you are still having trouble, please follow up here with details on what you've done so far, and what specific errors you are seeing.

Ken

**Comment by scurdy** [comment]
Hi Ken,

Thanks for you fast reply.
You answer is what I feared actually that I have to solve each dependencies one by one and which even means in some cases to get source code and build for 32 bits architecture. to be honest I am not a cmake expert and I already hit the wall trying to build "curl" from source code. I'll try to get some help from a skilled developer, I am a DSP guy with limited SW knowledge. Anyway, thanks for your help. As inspiration, I'll try to read the Rasp Pi guideline documentation it might help me out.

Sebastien

**Comment by kencecka** [comment]
Hi Sebastien,

Dependencies can certainly be a challenge.  The Raspberry Pi guide doesn't give a lot of direction on building dependencies any more, because they generally all come pre-compiled with the Stretch release.  However, there is an older version of the guide which you can access [here](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide/cde927bec023b2031ee0f8cf65a5ff117775dfd3) that has more detailed instructions on compiling all of the dependencies.

I'll go ahead and close this issue for now, but feel free to reopen if you have further questions.

Ken
