### ISSUE TITLE
Will the sdk support the en-CA locale at some point?

### ISSUE THREAD

**Issue by D3rpi** [alexa/avs-device-sdk#359]
Hello,
I switched from the avs sample app to this SDK last weekend because I was having issues accessing the skills on my account. My account switched to alexa Canada(after the rollout) but the SDK is on the US version. Will this SDK support the Canada version at some point?
I used the en-CA  locale in my json config but I am not sure it made a difference. 

https://github.com/alexa/alexa-avs-sample-app/issues/1018

**Comment by kencecka** [comment]
Hi @D3rpi,

The locale configuration can be a little bit confusing, and it's quite possible that you have not switched your locale yet, in spite of having changed your json config.  The value you specify in the json config only specifies the default locale to be used the first time you run SampleApp.  When SampleApp starts up, it uses that default, and writes it out to the settings database.  Any subsequent time you start SampleApp, it will use the value from the database, and ignore any changes you make to the json config.

If the database has already been written, there are two ways you can change the locale:
1. Use the keyboard inputs to select a different locale.  This is reached by selecting settings ('c'), locale ('1'), and then the locale you want to change to.  en-CA is not currently listed as an option, so you would also need to edit SampleApp/src/UserInputManager.cpp, and add an entry for en-CA to the LOCALE_VALUES map.
2. Edit your json config to specify en-CA as the default, and then delete your settings database so that SampleApp will re-read the default and write it to a new settings database.

Ken

**Comment by D3rpi** [comment]
Thank you.  That worked. 
Does the Canada locale support amazon music? 
I keep getting amazon music is not supported on this device when I try to play amazon music. 
Does it need to be enabled manually?

**Comment by kencecka** [comment]
Great!  I'm not aware of any region-specific limitation on amazon music, but access to Amazon Music is currently restricted to Alexa-enabled devices that are approved for commercial distribution and use. To get it working, you'll need to contact your Amazon Business Development Representative to get started on the approval for Amazon Music.
