### ISSUE TITLE
SDK 1.3.0 SampleApp Playback Is Imcomplete

### ISSUE THREAD

**Issue by changyp6** [alexa/avs-device-sdk#383]
SDK 1.3.0
Alexa audio playback is imcomplete.
For example, "Alexa, where are you?"
Alexa: "I'm here, and my head is in the ...", The word "cloud" is not played.

It seems that every playback, the last few audio is not played.

**Comment by scotthea-amazon** [comment]
Hello changyp6,

That is very interesting, but we are not experiencing that ourselves.  Can you tell us more your configuration (hardware, OS, compiler)?  Also it may be helpful if you were to provide a DEBUG9 level log a session in which you were able to reproduce this problem.

Thank you for bringing this issue to our attention,
-SWH

**Comment by sanjayrd** [comment]
Hi @changyp6,

Are you using our GStreamer based MediaPlayer? If so, this may be related to how we turned off GStreamer audio timeline synchronization to account for poor MPEG-TS audio packet timestamping in order to get Audible working. On line [571](https://github.com/alexa/avs-device-sdk/blob/master/MediaPlayer/src/MediaPlayer.cpp#L571), you can try turning this to `TRUE` and seeing what happens. Alternatively, on line [797](https://github.com/alexa/avs-device-sdk/blob/master/MediaPlayer/src/MediaPlayer.cpp#L797), you can change the sleep duration.

Thanks,
Sanjay

**Comment by kclchan** [comment]
Hi @changyp6, were you able to test the suggested changes by @sanjayrd?

**Comment by frozenberg** [comment]
Hi @changyp6,

We haven't heard from you in a while, so I'm going to close this issue. Feel free to reply and reopen if you have any more info from implementing @sanjayrd's suggestion.

Fede

**Comment by changyp6** [comment]
@kclchan @sanjayrd 
Sorry for the late replay.
I must have missed the email from github.
I've tried again with SDK 1.5, such issue still exists.

And I tried the modification suggested by @sanjayrd on line 571 of MediaPlayer.cpp of SDK 1.3 (which is line 671 MediaPlayer.cpp of SDK 1.5), this modification fixes such issue.
