### ISSUE TITLE
run Alexa App in  ARM NXP successfully

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#432]
Thank all friends' support.

I have been build and run the ARM version of Alexa App.

i came from Taiwan , and my email is: the.captain.panther@gmail.com

**Comment by zeusshuang** [comment]
Hi @captainpanther ,
 
Could you share your platform and solutions :)

**Comment by captainpanther** [comment]
platform:yocto NXP 
solutions:cmake with cross-compile  & NXP toolchain

**Comment by subjectxbj** [comment]
Hi @captainpanther ,

Which "wakeup engine" are you using? Sensory or KittAI?

**Comment by cr1108x** [comment]
Hi dear captainpanther:
I also want run on the NXP ARM platform
Would you share your detailed solutions to me?
My email: 361467115@qq.com

Thanks!

**Comment by avp24** [comment]
@captainpanther On executing SampleApp on ARM platform, I get below error:
(SampleApp:25804): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:25804): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
1970-01-02 02:24:53.847 [  1] C SampleApplication:Failed to create media player for speech!
1970-01-02 02:24:53.847 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

Can you please guide me in this error.
Thanks!

**Comment by captainpanther** [comment]
Sure your all voice package cross compiled successfully

avp24 <notifications@github.com> 於 2018年9月25日 週二 下午7:02 寫道：

**Comment by avp24** [comment]
@captainpanther I could successfully cross compiled all gstreamer & gstreamer plugins. After successful avs sdk compilation libraries like libAudioPlayer.a, libMediaPlayer.a etc were also generated. I copied all these files on my board as well.
Am I missing any plugins file on my board? If yes, then where do I copy these files on board or can I provide path to SampleApp to include libraries from specific directory?

Thanks!

**Comment by captainpanther** [comment]
Sure source code can include the gstreamer library correctly?

avp24 <notifications@github.com> 於 2018年9月25日 週二 下午7:29 寫道：

**Comment by avp24** [comment]
@captainpanther before compiling avs sdk i compiled gstreamer. Otherwise while compiling avs sdk with gstreamer would have given errors at linking stage. How can i confirm sdk built correctly with gstreamer? I used below mentioned cmake command to build avs sdk:
cmake /home/ap/Desktop/VVDN_AVS/alexa/avs-device-sdk -DCURL_LIBRARY=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/curl/lib/libcurl.so -DCURL_INCLUDE_DIR=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/curl/include -DCMAKE_TOOLCHAIN_FILE=/home/ap/Desktop/VVDN_AVS/alexa/toolchain_generic.cmake -DSENSORY_KEY_WORD_DETECTOR=OFF -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/wake_word_kitty/snowboy/lib/aarch64-ubuntu1604/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/wake_word_kitty/snowboy/include -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/gstreamer -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/portaudio/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/portaudio/include -DCMAKE_PREFIX_PATH=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/alexa_build -DCMAKE_INSTALL_PREFIX=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/alexa_build -DCMAKE_BUILD_TYPE=DEBUG -Wno-dev

Thanks for your reply.

**Comment by captainpanther** [comment]
When avs sdk compile,it need audio field driver- portaudio,alsa ,gstreamer~.
But curl just is need by embedded systems in internet connecting.so you
want to remove curl from cmake.
Please you use default cmake command for avs sdk official method.

avp24 <notifications@github.com> 於 2018年9月25日 週二 下午10:06 寫道：

**Comment by captainpanther** [comment]
You need too much argument in cmake command.please add few command to more
command step by step.and confirm command 's correction.

2018年9月25日 下午10:50，"the.captain. panther" <the.captain.panther@gmail.com>寫道：

When avs sdk compile,it need audio field driver- portaudio,alsa ,gstreamer~.
But curl just is need by embedded systems in internet connecting.so you
want to remove curl from cmake.
Please you use default cmake command for avs sdk official method.

avp24 <notifications@github.com> 於 2018年9月25日 週二 下午10:06 寫道：

**Comment by avp24** [comment]
I have given the arguments based on the dependencies mentioned and Iibrary paths required for cross compilation. If any of the commands are removed then I faced errors while building avs sdk.
Can you please share the procedure executed by you?
Thanks!
