### ISSUE TITLE
AudioPlayer can't be stopped immediately when barge-in during iHR playing.

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#436]
Hi,
    I encountered an issue in SDK version 1.3.0: When I do a barge-in operation during iHR playing, the AudioPlayer can't be stopped immediately, it will still play more than 1 second. This was happened when I ask "play Kiss FM station from iHR"; but it didn't happen when I ask "play lady gaga station from iHR", so amazing.

I did a integration test to help duplicate the issue, I push the test code to [HERE](https://gist.github.com/boyce-xx/93214c995495f1fff10074733c78764c).

The test procedure as this:
1. Send a "play Kiss FM station from iHR" request audio to AVS.
2. Waiting for the Kiss FM station start playing.
3. Sleep for 10 seconds.
4. Send another request "What time is it" to AVS.
5. You will find that iHR is still playing more than 1 second.

If I send the first request with "play lady gaga station from iHR" instead of "play Kiss FM station from iHR", It works well.
Can you clarify the issue if it's related to SDK or not?
Thank you.

**Comment by BennyAvramson** [comment]
Hi @boyce-xx,

Thank you for the information. We will investigate the issue internally and see if we can provide a fix soon.

**Comment by sanjayrd** [comment]
Hi @boyce-xx,

Generally, we've found that live radio stations URLs are much slower to respond than artist stations, thus blocking our stream readers. This causes a lag in the system.

A potential fix has been provided by @zhm-nico-nico-ni in this [thread](https://github.com/alexa/avs-device-sdk/issues/447). Please try it out and let us know how it goes - essentially the fix just modifies the reader to timeout quickly rather than continuously block.

Thanks,
Sanjay
