### ISSUE TITLE
while SpeechSynthesizer audio Attachment was saved in SDS, when the attachment was rleased? because we are afraid of the memory leaks!!

### ISSUE THREAD

**Issue by cxt32** [alexa/avs-device-sdk#450]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by cxt32** [comment]
as the subject title, the speechsynthesizer audio attachment(binary audio data) was saved in sds. it occupied memory certainly. so, we want to know when the occupied memory will be released?
how we can release the memory manually?

**Comment by dhpp** [comment]
Hi cxt32, 

Within the SDK, we use the SDS within Attachments, in order to communicate the audio data between ACL and SpeechSynthesizer.  In short, once ACL has completed writing the audio data, and SpeechSynthesizer has completed reading the data, then the attachment is released, and therefore the underlying SDS.

To see in more detail, you may wish to view the AVSCommon/AVS/Attachment/AttachmentReader and AttachmentWriter code.  This is generally taken care by our use of std::shared_ptr, which provides reference-counted memory management.  Once the final instance of a std::shared_ptr is goes out of scope, the underlying memory (pointed to by the shared_ptr) is then released.

Hope this helps.  Please re-open if this does not answer your question.
