### ISSUE TITLE
Can Alexa talk other languages?

### ISSUE THREAD

**Issue by GYJohn** [alexa/avs-device-sdk#505]
Hello guys,
Alexa is working pretty well!
Can i configure it to speak German?

I didn't find anything for this option.

I am using the newst version of the sdk on a Raspberry Pi.

Thank ya

EDIT:
I found that:
https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/UIManager.cpp

How i can enter this configure mode?

**Comment by khassel** [comment]
see end of section 3.2 https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide#32-update-alexaclientsdkconfigjson

**Comment by GYJohn** [comment]
@khassel 
I tryed it.
Alexa is still speaking english and dont understand me

**Comment by khassel** [comment]
tested it again, can change Alexa-language by editing "locale" in AlexaClientSDKConfig.json and restarting the App (new token not necessary). German settings are "locale":"de-DE"

**Comment by GYJohn** [comment]
@khassel
I did exactly this.. Still only english

**Comment by khassel** [comment]
sorry, no further idea at the moment ...

**Comment by GYJohn** [comment]
@khassel

Should i maybe try ur docker container?

**Comment by khassel** [comment]
you can test it with docker if you want to do this setup. The AlexaClientSDKConfig.json in my repo uses other paths, so better use the template provided there and fill it with your values.

**Comment by khassel** [comment]
yes alexa_sdk_docker

**Comment by celinval** [comment]
Hi @GYJohn,

The configuration saved in the database takes precedence over the .json file configuration. In order to reconfigure locale after you have ran the sample app at least once, you can do one of the following:

- Use the interactive menu. Press 'c' followed by Enter key to enter the settings menu. Follow the settings menu instructions printed in console.
- Delete your old settings.db file. The sample-app will create a new settings.db file and use the value from your AlexaClientSDKConfig.json

Please let me know if that works for you.

**Comment by celinval** [comment]
When you say Alexa, you should not expect any sound, but you should see the following message in the console:

############################
#       Listening...       #
############################

**Comment by GYJohn** [comment]
Yeah i can see this message.
So there is no option for enabling sound after 'Alexa'?

**Comment by celinval** [comment]
No, there isn't one. Just the visual cue.

**Comment by GYJohn** [comment]
Okey, thanks!
The last question..
Is the SDK on a pi compatible with Phillips Hue?

**Comment by celinval** [comment]
As long as it is Alexa enabled, I don't see any reason why it would not work with the SDK.
