### ISSUE TITLE
AVS CPU loading

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#540]
## Briefly summarize your issue:

I compared the V1.5/1.4 and older version (V1.2 or older), I found the CPU usage seems higher in new SDK. Maybe it's because it creates more threads in new SDK or other new algorithm.

I would like to know if there is any parameter or timer I can change and see if it will impact the CPU usage? Maybe it will cause response lower, it's okay, just some experiments.

## What behavior are you observing?

CPU usage seems have addition 5-10% than old SDK.

## Provide the steps to reproduce the issue, if applicable:

AVS idle
AVS Q&A
AVS play music

### What version of the AVS Device SDK are you using?
      1.5.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X] Other - tell us more:  embedded ARM platform.

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kencecka** [comment]
Hi @zeusshuang,

I couldn't tell you exactly what is contributing to the increased load you are seeing without going through a detailed profiling exercise, but if you are primarily noticing the difference in releases after 1.2, it is likely due to some refactoring of MediaPlayer.  Up through 1.2, when the SDK needed to play content from a URL, it simply passed that URL into gstreamer, and let gstreamer go out and fetch the data.

Starting in release 1.3, we pulled the networking piece of that out of MediaPlayer.  The URL is fetched using libcurl, and then the resulting data is passed to gstreamer.  This change was made to ensure all networking in the SDK goes through the same stack.  We have not made a detailed analysis of the performance in this new implementation, but it is possible that you are seeing a small load increase as a result of it.

I should also note that we are continuing to optimize the URL streaming for MediaPlayer, so you should see improvements in future releases.

Ken

**Comment by zeusshuang** [comment]
Hi @kencecka ,

Thanks for the comment! The information is helpful.
I am comparing the impact on AVS while setting different system loading and Internet conditions.
It's because it seems impact the playing music, so I am wondering the changes between older SDK (before 1.2) and new.

**Comment by sanjayrd** [comment]
Hi @zeusshuang,

A more detailed log of changes in every SDK release can be found [here](https://github.com/alexa/avs-device-sdk/blob/master/CHANGELOG.md).

Thanks,
Sanjay
