### ISSUE TITLE
How to make Alexa listening, when i say a hotword?

### ISSUE THREAD

**Issue by YanLiudchyk** [alexa/avs-device-sdk#554]
Does it possible to make Alexa listening, when i say a hotword?

**Comment by shawngiese** [comment]
Yes, but i think you can only use "Alexa".

**Comment by YanLiudchyk** [comment]
How I can do this?

**Comment by shawngiese** [comment]
It is part of the default configuration for the Raspberry PI (that is what I use). You must have a USB microphone that matches the specs. I just used a logitech web cam. There are various audio commands you can use to test that your audio hardware is working. Once I start the sample app it is listening on the microphone.

**Comment by scotthea-amazon** [comment]
Hi YanLiudchyk,

There are different instructions for setting up the SDK on different platforms.  You can find them in the [Get Started Section](https://github.com/alexa/avs-device-sdk#get-started) of out documentation.

As shawngiese mentioned, the hotword (we refer to it as wakeword) is enabled by default for Raspberry Pi, using our [Raspberry Pi Quick Stat Guide](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script).

For other platforms, you will need get a wakeword detection library from an external provider.  We support integrations of the [Sensory](https://github.com/Sensory/alexa-rpi) and [Kitt.ai](https://github.com/Kitt-AI/snowboy/) libraries.  See the [Build With Wakeword](https://github.com/alexa/avs-device-sdk/wiki/Build-Options#build-with-a-wake-word-detector) section of our documentation for instructions on enabling these integrations.

Thank you,
-SWH

**Comment by cucubits** [comment]
Hi, 

I have a similar question and I'd like to try asking it here instead of opening another issue. Was the latest SDK release tested and found working with the current Kitt.ai wakeword engine?

Would it be possible to provide a scripted install for the SDK on a Raspberry Pi, similar to the current one but with Kitt.ai instead of Sensory?

On the same idea, even just the quick start guide updated with more detailed steps to get it working with Kitt.ai would be very helpful. 

I've tried with the kitt.ai make instructions from the Build Options page but I am missing something as I always get some compile errors near the end of the process. I am sure it's something simple as not downloading the proper files from Kitt.ai or wrong paths.

Thank you!

**Comment by scotthea-amazon** [comment]
Hi cucubits,

I expect the latest version was tested with 1.6, but do not have solid evidence.  Are you experiencing a problem with 1.6 that was not there in a previous release?

There is not much we can do to help with an unspecified compile error.  Can you provide a log showing the build process and errors?  If so, it would be best to file a separate issue with an appropriate title so that other can find it if they are having similar issues.

As for improving the documentation for setting up kit.ai - thank you! - that is very helpful feedback.

Regards,
-SWH

**Comment by cucubits** [comment]
Thank you. At some point I will open a separate issue. For now I'm testing Alexa with the default Sensory engine. It works flawlessly, you guys did a good job with the pi install script. My only reason for wanting to go with kitt.ai was the possibility of custom wake words but being new at this, I've ran into some limitations of the sample app. My idea was to use it to control other connected devices but so far I've heard too many times from her "I'm sorry, that is not supported on this device".

**Comment by scotthea-amazon** [comment]
Hi cucubits,

At the moment, the AVS Device SDK is primarily concerned with providing an Alexa voice experience with your device.  There are a variety of ways to control devices from Alexa.  You may find [this link](https://developer.amazon.com/alexa/connected-devices) helpful.

Thank you,
-SWH

**Comment by kclchan** [comment]
@YanLiudchyk, I'm closing this issue now, but please reopen if you're still having further questions.  Thanks!
