### ISSUE TITLE
AVS running 2 hours exit.

### ISSUE THREAD

**Issue by lukunnr** [alexa/avs-device-sdk#595]
Hi
    AVS running for about 2 hours,AVS exit, what is the cause of this?Is there any solution?
If the network has a failure to give the warning, the network can continue to serve instead of directly exiting.

### What version of the AVS Device SDK are you using?
      1.6.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more: armv7

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

log:

#############################
#       Connecting...       #
#############################

2018-03-27 17:50:15.437 [  8] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-03-27 17:50:15.437 [  8] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=0,retryBackoff=252
2018-03-27 17:50:15.693 [  8] E HTTP2Transport:networkLoopRetryingToConnect:reason=establishConnectionFailed,retryCount=1,retryBackoff=1010

**Comment by priyagsenthil** [comment]
Hi,

The SampleApp has been run successfully overnight in our stress tests. So what exactly was it doing it when it crashed - was there no network connectivity for a long time and after a period of no network connectivity for 2 hours the SampleApp crashes. The log provided just seems to suggest that the network loop is trying to reconnect with increasing time intervals which is the expected behavior.  Please advise.

Thanks
Priya
