### ISSUE TITLE
avs-device-sdk on Rapsberry Pi installation issues

### ISSUE THREAD

**Issue by canbu** [alexa/avs-device-sdk#617]
avs-device-sdk installation issue on Raspberry Pi3 (with Raspbian Stretch) :

as per these instructions :
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

Installation does n't work. Cloning avs-device-sdk always hangs after completing 99%...tried several times...cloning does n't work at all..

also tried step-by-step installation...that has different issues...it fails on avs authorization .json script even though all credential info are correct...could n't find the .db files referenced in the script in the said directories..may be they are not getting downloaded?

**Comment by BennyAvramson** [comment]
Hi @canbu,

If cloning hangs, it's probably related to your network quality. Since you're saying you can complete cloning manually, I suggest to start running the script, then assuming cloning hangs, cd into the local repository and complete the cloning manually. Then edit the `setup.sh` script and comment out the `git clone` line.

Please note that you'll also have to remove other folders created by the script.
Finally, rerun the script.

Please let me know if that solves the issue.

Thanks,
Benny

**Comment by canbu** [comment]
thanks..will try it..

**Comment by canbu** [comment]
manually cloning worked...and I could build..
now the issue is with authorization (as I mentioned before).
get this error repeatedly when I run the script sudo bash startauth.sh : (my config.txt file has all correct data)

The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

**Comment by canbu** [comment]
further to the above issue: 

when I try to open http://localhost:3000/ which directs to amazon login page and after signing in to that page , this error pops : (I believe itś due to refresh token which has not yet been granted)

I noticed few others too had faced this issue but no looks like fixes so far?

Why the authorization does nót go through? 
I find the AlexaClientSDKConfig.json script refers to few files in db directory but there are no such files there 
(the files referred in the json script are : /home/pi/avs/db/alerts.db, /home/pi/avs/db/certifiedSender.db, /home/pi/avs/db/settings.db, /home/pi/avs/db/notifications.db)
Should these be present in the db directory? How by whom are they loaded?

the error :

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

**Comment by canbu** [comment]
further to the above issue:

when I try to open http://localhost:3000/ which directs to amazon login page and after signing in to that page , this error pops : (I believe itś due to refresh token which has not yet been granted)

I noticed few others too had faced this issue but no looks like fixes so far?

Why the authorization does nót go through?
I find the AlexaClientSDKConfig.json script refers to few files in db directory but there are no such files there
(the files referred in the json script are : /home/pi/avs/db/alerts.db, /home/pi/avs/db/certifiedSender.db, /home/pi/avs/db/settings.db, /home/pi/avs/db/notifications.db)
Should these be present in the db directory? How by whom are they loaded?

the error :

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

**Comment by dhpp** [comment]
Hi @canbu, two details to consider:

1) please add the https variants to your return uris as well as http.
2) ensure the script is running when you perform the login via the web browser.

Let us know if this helps.

**Comment by canbu** [comment]
yes, the profile already had both https & http variants
The script was of course running...
just tried again..same error..

**Comment by canbu** [comment]
I'm surprised...why so many basic issues on just getting the Application installed and working...my board is a fresh, good board proven to work...the Raspian Stertch is also a freshly installed one which I believe has no issues..

How come the same Application works for many others and not on this board which is perfectly a good one..
Anything to do with this Application software version? If so, please let me know the working version so that I can get something to work with..
Thanks..

**Comment by canbu** [comment]
I exactly did that before. Created a second avs device as described...same issues..

I also have my another of my own custom hardware (not RaspPi) and these authorization steps were done in one go and everything worked in just one try. But not so here with RaspPi3 board...
Anyway, will try these again one more time soon...

**Comment by dhpp** [comment]
Thanks.  Let us know if you need further input from us.

**Comment by bwanaaa** [comment]
same problem here. Followed the tutorial here:

[https://www.hackster.io/matrix-labs/matrix-voice-and-matrix-creator-running-alexa-c-version-9b9d8d](url)

using the prebuilt alexa-pi image
edited the config.txt file
got this

%bash startauth.sh
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

don't know what to look for in 'top' to test that the server is running

However this works

wget http://127.0.0.1:3000

it downloads a whole amazon page

--2018-04-27 00:50:07--  http://127.0.0.1:3000/
Connecting to 127.0.0.1:3000... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://www.amazon.com/ap/oa/?scope=alexa%3Aall&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthresponse&response_type=code&client_id=amzn1.application-oa2-client.77b3100e335b4425b374b04d10a6f26a&scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22Cutsie1%22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%22127654%22%7D%7D%7D [following]
--2018-04-27 00:50:07--  https://www.amazon.com/ap/oa/?scope=alexa%3Aall&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthresponse&response_type=code&client_id=amzn1.application-oa2-client.77b3100e335b4425b374b04d10a6f26a&scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22Cutsie1%22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%22127654%22%7D%7D%7D
Resolving www.amazon.com (www.amazon.com)... 13.33.37.88
Connecting to www.amazon.com (www.amazon.com)|13.33.37.88|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.amazon.com/ap/signin?_encoding=UTF8&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.pape.max_auth_age=0&ie=UTF8&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=lwa&openid.assoc_handle=amzn_lwa_na&marketPlaceId=ATVPDKIKX0DER&arb=6da128d7-78bb-4529-bf4a-d985249b6a15&language=en_US&openid.return_to=https%3A%2F%2Fna.account.amazon.com%2Fap%2Foa%3FmarketPlaceId%3DATVPDKIKX0DER%26arb%3D6da128d7-78bb-4529-bf4a-d985249b6a15%26language%3Den_US&enableGlobalAccountCreation=1&metricIdentifier=amzn1.application.e84eb55fa37645699897712afc3ec9ca&signedMetricIdentifier=rOKatWq8snkVK%2FyDFUDk96Y4lle%2BDqr1yLUmlVq20cE%3D [following]
--2018-04-27 00:50:07--  https://www.amazon.com/ap/signin?_encoding=UTF8&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.pape.max_auth_age=0&ie=UTF8&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=lwa&openid.assoc_handle=amzn_lwa_na&marketPlaceId=ATVPDKIKX0DER&arb=6da128d7-78bb-4529-bf4a-d985249b6a15&language=en_US&openid.return_to=https%3A%2F%2Fna.account.amazon.com%2Fap%2Foa%3FmarketPlaceId%3DATVPDKIKX0DER%26arb%3D6da128d7-78bb-4529-bf4a-d985249b6a15%26language%3Den_US&enableGlobalAccountCreation=1&metricIdentifier=amzn1.application.e84eb55fa37645699897712afc3ec9ca&signedMetricIdentifier=rOKatWq8snkVK%2FyDFUDk96Y4lle%2BDqr1yLUmlVq20cE%3D
Reusing existing connection to www.amazon.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                        [ <=>                                              ]  32.45K  --.-KB/s    in 0.01s

2018-04-27 00:50:07 (2.69 MB/s) - ‘index.html’ saved [33225]

**Comment by bandkenamazoncom** [comment]
Can we close this one and if you have further problems, open a new issue.  It makes it easier for others to use this as a resource.

**Comment by bwanaaa** [comment]
Of course, I’m ok w closure.

**Comment by scotthea-amazon** [comment]
Closing issue per previous discussion.  Please feel free to re-open if it has been closed in error.

**Comment by Haddybaba123** [comment]
I also have the same problem first I was stucked at 93% then after writing various commands and decresing the graphics memory it started but then got stucked on 95% please help waiting from a month and I have also written the same thing on the stackoverflow but no response please please and please help me out

I am following the instructions on https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html
