### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#654]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi,
In the AVS SDK, the volume control is actually using the gstreamer "volume" plugin to adjust the volume of the audio sound. But it does not affect the real HW sound card control. For a Alexa enabled device, there are 2 buttons "volume up" and "volume down". 

So what should these buttons control. Should it also control the "volume" plugin, or should it control the sound card directly? 

Currently our sound card does not support volume control, so I'm using the volume buttons to control the "volume" plugin. But it seems the volume restore to 100 in a new session.

Can you clarify?

Thanks

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bandkenamazoncom** [comment]
Good question!

The buttons should control the volume through the SpeakerInterface.  In the SampleApp, the MediaPlayer implements the Speaker, so that's where the volume control is done.  The speaker portion could be factored out to go directly to the audio hardware.

As for the reset to 100, can you give more context?  Do you set it to 50 and restart the SampleApp and it gets set to 100 again?  The SampleApp doesn't maintain the volume between restarts.  That is something that is up to the implementer.

**Comment by subjectxbj** [comment]
Hi @bandkenamazoncom,
Not by restarting the SampleApp. When I adjust the volume to 50 during playing a music, the volume adjust works. But when I play another music, the music  will be playback at volume 100.

This behavior seems different from Amazon Echo. When I use button to adjust volume on echo. All the playback sounds including response, music playing, and sound cue will use the adjusted volume.

**Comment by bandkenamazoncom** [comment]
What do you mean by playing a music and playing another music?

Again, the SampleApp doesn't persist the volume across restarts.  It's not a drop in replacement for the Echo, but a full-featured example of an Alexa client.
