### ISSUE TITLE
How to set up AVS on Raspberry Pi with bluetooth speakers

### ISSUE THREAD

**Issue by PavelYarysh** [alexa/avs-device-sdk#713]
Hello, can anyone please help me?
I installed avs on raspberry pi and the sample app works perfectly, now I want to use it with bluetooth speaker as output and usb microphone as an input. I performed all the actions from this link https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide  under Bluetooth section, however my output is still going to the monitor's speakers.

**Comment by priyagsenthil** [comment]
Hi PavelYarysh,

Could you run the SampleApp at debug level DEBUG9 and provide the logs.

Thanks
Priya

**Comment by priyagsenthil** [comment]
Also, what exactly do you mean by "I want to use it with bluetooth speaker as output". Current release of bluetooth in AVS SDK only support A2DP-SINK and not A2DP-SOURCE. Please advise.

Thanks
Priya

**Comment by kjkh** [comment]
Hi,

To re-iterate, the SDK does not currently support acting as an A2DP-SOURCE, ie sending music to another device. 

If you wish to use the Bluetooth speakers outside of Alexa and the SDK, it is likely the Raspberry Pi will already support that. You can try by re-enabling BlueALSA (or PulseAudio if you have it installed), and building the SDK without Bluetooth. Then, pair and connect the Bluetooth device to your system as normal (outside of the SDK). The SDK sends all audio to the underlying system to handle, thus configuring the Pi to route audio to your device will allow you to use the Bluetooth speakers to play all the SDK audio. There's typically a GUI window to select which output device the Pi sends its audio to. Since this operates outside of the SDK, you will not be able to use Alexa to perform any Bluetooth commands.

Closing ticket, please feel free to re-open if there are further questions.
