### ISSUE TITLE
Creating custom alexa voice commands

### ISSUE THREAD

**Issue by sriranjanr** [alexa/avs-device-sdk#721]
Hello,

I want to be able to use custom voice commands for my application. Like 
"Alexa, turn on left light"
"Alexa, turn on right light"
"Alexa,take a photo"
"Alexa,start recording video"
"Alexa, end video recording"..

How do I create these customs commands? I read here [https://forums.developer.amazon.com/questions/101288/how-to-add-the-custom-commands-in-alexa-in-raspber.html](https://forums.developer.amazon.com/questions/101288/how-to-add-the-custom-commands-in-alexa-in-raspber.html) we cannot create custom commands except those given in the skills set.

**Comment by sriranjanr** [comment]
I looked at the amazon developer guide and it seems we can create customs skills but now my question is this. Say I ask alexa the question "Alexa, turn on the left light". What response will alexa give me to this question so that I can link it to the code to turn on a GPIO pin on Raspberr Pi 3. How do I use this custom skill and its response to control GPIO in Raspeberry pi 3 in the SampleApp cplusplus code.

**Comment by mavamazon** [comment]
Hi!

In general you have to implement your own server side code to handle the interaction with Alexa. SDK will have only the audio representation of the answer from Alexa. I encourage you to investigate Alexa Skill Kit more, probably by starting here: https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html

Andrey.

**Comment by dottantgal** [comment]
Hi @sriranjanr , Did you find a way to add your own skills to your own Alexa device?<br>
I've followed this guide https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide but now i dont know how to use my own skill which are already set on my amazon dev account (and which i can use with the skill tester and running a bespoken server) <br>
Thanks in advance

**Comment by kencecka** [comment]
Hi @dottantgal,

In general, Alexa is designed so that skills will work on any device, and devices do not need to change their firmware to support new skills.  This means that the AVS interface is constrained to operations primarily related to audio-in and audio-out.  Other device-specific features need to be implemented through some other path.

One common way to do this is to create a custom skill, and then use AWS-IoT to send message from your skill to your device.  The voice input and alexa audio responses are handled by AVS, and the device-specific control is handled through IoT.  If you have further questions about how to set this up, you might want to ask on the [Alexa Skills Kit forum](https://forums.developer.amazon.com/topics/alexa+skills+kit.html) or [Alexa Smart Home forum](https://forums.developer.amazon.com/topics/alexa+smart+home.html), [AWS IoT forum](https://forums.aws.amazon.com/forum.jspa?forumID=210).

Ken

**Comment by dottantgal** [comment]
Hi @kencecka 
I solved it weeks ago, so, could you please now answer to my #764 issue?? It's really important cause the code is not commented and it's impossible to understand things within it.
Thank you so much.
