### ISSUE TITLE
Some issues in AVS functional self test checklist

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#815]
Hi AVS team,

AVS SDK 1.7.1
Here are some issues in AVS functional_self-test-checklist_v1.9
Could you have comments ?

Section 5:
case 5.3: It will respond "Savaan is not supported on this device"
Section 8:
case 8.1: Take Device 1 offline by powering down. It's strange that AVS will not show offline after 1 minutes on APP (will wait about 10 minutes), but Echo will be.
case 8.1: other case, Is the DOD support now ?

**Comment by priyagsenthil** [comment]
Hi zeusshang,

We have already run through the checklist and have the SDK certified. We will redo the tests and report the findings.

Thanks
Priya

**Comment by priyagsenthil** [comment]
Hi Zuesshang,

Please see our findings below

Section   5: 
case   5.3: It will respond "Savaan is not supported on this device" 
 Savaan should be enabled for the device type that you are testing. If not this is the expected behavior. 

Section   8: 
case   8.1: Take Device 1 offline by powering down. It's strange that AVS will not  show offline after 1 minutes on APP (will wait about 10 minutes), but Echo   will be. 
Which platform are you seeing this. We tested on Linux and PI and it is immediate. For mac I have seen it stays online but once you refresh app the status changes to offline. This is again not an SDK issue.

case   8.1: other case, Is the DOD support now ? 
What is DOD? Could you elaborate on the use case.

Thanks
Priya

**Comment by zeusshuang** [comment]
Hi @priyagsenthil ,

Sorry for the confused, the DOD is "do not disturb" case. I think "case 8.1" is for this case.
It's because we will go into Amazon Lab, we just want to clarify which is SDK issue, and which cases we can ignore due to server site issue.

**Comment by zeusshuang** [comment]
Hi @priyagsenthil ,

About case 8.1 the offline will be detected by APP for 10 minutes, I ever raised this case at #616 , and it said 10 minutes is expected.
Actually, if we suddenly power off the AVS client, I think it should be not SDK issue, right ?
If it's not, it does not make sense to define this test case in Amazon self test.

**Comment by leino11121** [comment]
Hi Zeus,

I'm developer from China, I guess you too. 

If you can, can you add me WeChat, we can exchange the experience of AVS certification.

WeChat: leino11121
Email: leino11121@163.com

BTW, I have the same issue for the notification, but I cant wait avs team to fix it, so I change some code on the sdk. It works fine for now.

**Comment by scotthea-amazon** [comment]
Hi zeusshuang,

I am sorry to see that this issue has been languishing unanswered for a very long time.  Is this still an issue?  Do you still need us to double check something, or should we close this?

Thank you,
-SWH

**Comment by zeusshuang** [comment]
Hi @scotthea-amazon ,

We can close this case now.
If I got the same issue again, I will create another ticket.
Thanks,

**Comment by scotthea-amazon** [comment]
Thank you Hi zeusshuang.  I am closing the issue.
