### ISSUE TITLE
Voice response is incomplete

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#839]
Hi AVS team,
 
SDK 1.8 , ARM based OpenWRT embedded linux.

We got many reported that the voice response is incomplete or cut off.
Sometime it happens while barge-in during playing Music, sometimes it's from normal Q&A case.
Here I attached a log from barge-in case.
While playing music, say: Alexa, Thumbs down.  It response "okay", but from APP History, it should respond "okay rating saved".

[19541-cc1d849774154846b9c75a02703bb28d.txt](https://github.com/alexa/avs-device-sdk/files/2179822/19541-cc1d849774154846b9c75a02703bb28d.txt)

**Comment by zeusshuang** [comment]
Hi @kclchan ,

By tester, the timestamp is about 2018-07-09 03:42, where you will see a "KeywordObserver" log, it's barge-in, the response cut off should happens after this barge-in

**Comment by kclchan** [comment]
Hi @zeusshuang,

Thanks for providing the timestamp, it's extremely helpful.  I am looking at the logs now, and will get back to you ASAP once we find anything.

Thanks,
Kenneth

**Comment by kclchan** [comment]
Hi @zeusshuang,

Based on the logs:

018-07-09 03:42:35.665 [  b] 0 DialogUXStateAggregator:transitionFromThinkingTimedOut
2018-07-09 03:42:35.798 [  3] 0 MediaPlayer:callingOnTags
2018-07-09 03:42:35.798 [  b] 0 DialogUXStateAggregator:setState:from=THINKING,to=IDLE
2018-07-09 03:42:35.799 [  3] 0 MediaPlayer:callingOnPlaybackStarted:currentId=260
2018-07-09 03:42:35.799 [  3] C SpeechSynthesizer:onPlaybackStarted:METRICS::Location=SpeechSynthesizer Receive,NAME=SpeechStarted

The speech is cut off due to getting transitionFromThinkingTimedOut before the SpeechSynthesizer start speaking.  There appears to be a race condition and we have created an internal ticket to track and fix this issue ASAP.

Thanks again for letting know about this issue and providing the logs for it.

Thanks,
Kenneth

**Comment by zeusshuang** [comment]
Many thanks for your comments !

**Comment by jpatu001** [comment]
Hi All,

Is this issue resolved? I may have a similar issue. When cancelling a timer/ alarm, the response I get is "Timer for 10..." then gets cut off instead of "Timer for 10 seconds cancelled". My logs show that the transition I have when cancelling is Listening->Thinking->Idle->Speaking->Idle. This is on sdk v1.8.1 embedded linux..

Thanks,
jpatu001

**Comment by jan4984** [comment]
yes I have this problem in some arm Linux board . is this a issue of gstreamer? https://lists.freedesktop.org/archives/gstreamer-devel/2015-March/052131.html

please any one know gstreamer  can help fix this for avs-device-sdk?

**Comment by jan4984** [comment]
I found that the version 1.5 sdk 's  sleep works in 1.7.1. not know why amazon remove it.

MediaPlayer.cpp:

    case GST_MESSAGE_EOS:
        std::this_thread::gp_for(std::chrono::milliseconds{500});

**Comment by zeusshuang** [comment]
Hi @scotthea-amazon ,

Thanks!! I will merge this release and try it.

**Comment by KrisBird** [comment]
I just installed 1.10 on a fresh Raspberry Pi3 Stretch and the response is cut in the start.

**Comment by kclchan** [comment]
Hi @KrisBird, is your audio being output via HDM?  If so, could you try using a headphone jack instead?

**Comment by kjkh** [comment]
Hi @zeusshuang,

Are you still experiencing this issue after updating?

@KrisBird, are you still seeing the issue after switching audio output to the headphone jack?

**Comment by zeusshuang** [comment]
Hi @kjkh ,
so far I did not see this problem in SDK1.11.

**Comment by KrisBird** [comment]
I never found a reason for it not working and I ended up reinstalling. After that no problems :-)

**Comment by visayamv** [comment]
Looks like this issue is no longer existent. I am closing this issue, please reopen if you need more assistance regarding this.
