### ISSUE TITLE
Capabilities API

### ISSUE THREAD

**Issue by Piflyer** [alexa/avs-device-sdk#857]
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: AIY Image powered by Raspbian Stretch

Hi, I want to make my Raspberry Pi like an Echo Show so that when I say "Alexa", it comes up a display card with the information, like the weather. So basically render a card. However, I read [this](https://developer.amazon.com/docs/alexa-voice-service/templateruntime.html) and it said to include it in the Capabilities API. I search through the files, and couldn't find it. Where should I declare it, and how am I suppose to make it run? Thanks.

**Comment by BennyAvramson** [comment]
Hi @Piflyer,

The SDK already implemented the client code for TemplateRuntime Capability Agent. 
If you want to render the display cards on a screen, the best way would be changing the [GUIRenderer](https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/GuiRenderer.cpp) class which currently just prints to console.

Let me know if you have more questions.

Thanks,
Benny

**Comment by Piflyer** [comment]
Where do I change it so that it can run?

**Comment by BennyAvramson** [comment]
I suggest to start here [GuiRenderer::renderTemplateCard](https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/GuiRenderer.cpp#L61).

This function receives the payload which includes the JSON of the display card.

Thanks,
Benny

**Comment by Piflyer** [comment]
Is there a command to make it start?

**Comment by Piflyer** [comment]
How can I make the display cards appear on the Raspbian Desktop?

**Comment by dhpp** [comment]
Hi @Piflyer - sorry this ticket was not updated in a while.  The short answer is that our SDK does not provide actual GUI rendering, since that will vary across platforms.  However our console SampleApp provides the hooks for you to do this, which you may find in the GuiRenderer class, which receives all the metadata associated with a card to be rendered.

I'll close this ticket out for now - please update to our 1.10 release, and open a new ticket if you have further questions, thanks.
