### ISSUE TITLE
Voice response is cut off while barge-in during music is playing

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#863]
Hi AVS team,

SDK 1.8.1 , ARM based OpenWRT embedded linux.

Steps:
Alexa, play music
Alexa, what's the weather
--> sometimes, the weather answer is cut off and music start playing.

This issue cannot be produce 100%, but have chance to see this case.
Please help to check attached log, I got a fail case after several trials.

[AVSPARTNER-6263.txt](https://github.com/alexa/avs-device-sdk/files/2212377/AVSPARTNER-6263.txt)

**Comment by BennyAvramson** [comment]
Hi @zeusshuang,

I've followed the steps you described several times, but I couldn't reproduce the cut-off.
Any chance you could reproduce it with DEBUG9 enabled?

Thanks,
Benny

**Comment by zeusshuang** [comment]
Hi @BennyAvramson ,

I will try it. It's really not easy to reproduce this case. The log I attached is a lucky I got it one time.

Thanks,

**Comment by celinval** [comment]
Hi @zeusshuang,

From the logs you provided, this seems to be a timeout issue. Even though the speech synthesizer moves to playing state, it is not fast enough to notify the DialogUXStateAggregator. Thus, the DialogUXStateAggregator transitions from THINKING to IDLE which will cause the speech synthesizer to later stop the weather report.

You might be able to avoid that issue by increasing the timeout on [DialogUXStateAggregator.cpp (SHORT_TIMEOUT)](https://github.com/alexa/avs-device-sdk/blob/add1956688ea777e3632d3006fc2171efe7b5620/AVSCommon/AVS/src/DialogUXStateAggregator.cpp#L37).

Please let me know if that works or if you can get DEBUG9 logs for this issue so we can confirm the root cause.
