### ISSUE TITLE
Template Runtime Help

### ISSUE THREAD

**Issue by Piflyer** [alexa/avs-device-sdk#894]
Hi, earlier, I posted an issue on Capabilities API, and the display cards. I was able to declare what I needed with the Capabilities API, and I was also showed with the template runtime c++. Now, I want to make the output of it a User interface, or a visual, so that it looks and runs like an echo show. However, reviewing the file, it outputs c++ and displays text. How do I make it a visual, and also interactive? Thanks!
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more: AIY Image powered by Raspbian

**Comment by kjkh** [comment]
Hi @Piflyer,

You need to create an instance of` avsCommon::sdkInterfaces::TemplateRuntimeObserverInterface`, which you can register through the DefaultClient's `addTemplateRuntimeObserver()` method. An example of this is shown in SampleApplication.cpp. We also have an example renderer, GuiRenderer.h and GuiRenderer.cpp, which demonstrates the interfaces you need to implement in order to receive the templates in JSON format. You can then render and display them in the manner of your choosing.

There is currently no support for interactive templates.

**Comment by Piflyer** [comment]
I looked into GuiRenderer.h and it said that it will print out the JSON instead of runing it, so is there a way to make it run the JSON instead? Thanks

**Comment by kjkh** [comment]
Hi @Piflyer,

With 3P products, the JSON that you see is what AVS sends the client; it is up to the client to then render it. This section on [Display Cards](https://developer.amazon.com/docs/alexa-voice-service/ux-design-overview.html#displaycards) contains details on the requirements around the rendered cards.

You will need to use some sort of graphical library in order to do so; there is not an example of this in the SDK. The AVS SDK only demonstrates rudimentary rendering by directly printing out the JSON received from AVS.

**Comment by kjkh** [comment]
Yes, the data sent to the client is regular JSON. Can you elaborate on what you mean by "any other AVS stuff, or need to declare the AVS program"?

**Comment by Piflyer** [comment]
Basically, I meant that do I need to import any files to the JSON file? Plus, all I need is to turn the JSON and executed, right?

**Comment by kjkh** [comment]
Yes, if I understand you correctly, the JSON will fully contain the correct data you need to render.  Please refer to the [TemplateRuntime API](https://developer.amazon.com/docs/alexa-voice-service/templateruntime.html) for a reference to the various JSON data you may receive.

**Comment by Piflyer** [comment]
Ok, Thanks! Also, does it have settings and other functions, or do I have to add to it?

**Comment by kjkh** [comment]
What would be an example of a setting or other function that you were thinking might need to be added?

**Comment by Piflyer** [comment]
Like in many devices, there is a settings function where you can adjust stuff like the screen lighting, volume, WiFi, etc.

**Comment by kjkh** [comment]
Yes, you will need to create those GUI elements independently of the Template Runtime Display Cards. Here is an [overview](https://developer.amazon.com/docs/alexa-voice-service/display-cards-overview.html#display-card-templates) of the types of display cards supported.

**Comment by Piflyer** [comment]
Also, do you know any programs that takes the JSON code from the C++ and run the json? Would Flask work?

**Comment by Piflyer** [comment]
Ok, so if I can convert the JSON values like the title to html, then I would be fine? Also do you know how to make it so that the devices is regonized with a screen so that videos can be played on it?

**Comment by kjkh** [comment]
HTML is one possible way to render it, but that will be dependent on which library and framework you eventually choose to use. AVS does not have requirements on the technology the device uses to render, only requirements around the final rendered content.

AVS does not currently support sending directives related to video playback.

**Comment by Piflyer** [comment]
Ok, I will try to do it. Is there an option to have this device have custom commands, like turning on internal lights, and stop airplay music?

**Comment by kjkh** [comment]
Hi, those features would be examples of ASK Skills. Depending on the skill, there may be requirements which the SDK does not yet support.
