### ISSUE TITLE
New notification state

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#897]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
The AVS SDK declared that it has passed the AVS certification. But how does it pass the new notification test?

The Certification requires there is a LED display for new notification, but actually there is only a Notification queued state in the SDK right now.

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @subjectxbj,

The UIManager implements the NotificationsObserverInterface and is subscribed to _onSetIndicator()_ updates. I tested with a sample notification, and the Notifications Capability Agent is correctly notifying it's observers. The following mimicking an "LED on" state was printed by the UIManager: 

################################################
#       NOTIFICATION INDICATOR STATE: ON       #
################################################

Can you elaborate what you mean by "there is only a Notification queued state in the SDK right now." ?

**Comment by kjkh** [comment]
Thanks for raising this!

The understanding is that you may optionally display a different "notifications arrived" visual indicator than the persisted visual indicator when you first receive a notification. However, having the same cue for both states is still acceptable. There would be little purpose for the SDK to have a separate logical state for this (something like IndicatorState::INITIAL), as the state transition is not in the control of the Notifications capability agent. It is entirely dependent on when the visual indicator renderer has rendered the initial "notification arrived" indicator, and will now need to render the persisted "notification queued" indicator.

Are you having troubles with the certification process due to this? If so, there appears to be some ambiguity around the expectations, and we can investigate and clarify.

**Comment by subjectxbj** [comment]
The certification team first raised this as a Blocker Issue. After we told them that SDK does not support this, then they are ok with it now. Thanks.
