### ISSUE TITLE
Not able to authorize

### ISSUE THREAD

**Issue by khassel** [alexa/avs-device-sdk#934]
################################################################################################
    #       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: {XXXX}       #
    ################################################################################################

After entering the code only a message is displayed, that a problem occured and they are working on it.
But the problem exists now for more than 12 h ...

**Comment by bennyAv10** [comment]
Hi @khassel,

Usually, this issue caused by a wrong productID in the json file. 
(If you installed the SDK with the installation script, you entered the productId to config.txt before running the script)

Please open `${_BUILD_PATH_}/Integration/AlexaClientSDKConfig.json` and make sure deviceInfo details are correct:

```
{
    "deviceInfo" : {
        "productId" : "<YOUR PRODUCT ID WHICH MAY BE WRONG>",
        "clientId : "<YOUR CBL CLIENT ID>",
        "deviceSerialNumber": "<YOUR DEVICE SERIAL NUMBER>"
    },
    [... other values]
} 
```

Please let me know, if that solves your issue.

Thanks,
Benny

**Comment by khassel** [comment]
Hi Benny,

that solved my issue, on that device the clientId was an old one ... but maybe you could provide a better error message in such cases ...

Thanks,
Karsten.
