### ISSUE TITLE
clone error during Install Sensory

### ISSUE THREAD

**Issue by uyanga46** [alexa/avs-device-sdk#94]
Hello,

I followed the Raspberry Pi Quick Start Guide. And the installation went well without a problem until the 2.7.2 Install Sensory step. Here I got this error when I clone the file:

pi@raspberrypi:~/sources $ git clone https://github.com/Sensory/alexa-rpi.git
Cloning into 'alexa-rpi'...
git-remote-https: symbol lookup error: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4: undefined symbol: nghttp2_session_callbacks_set_error_callback

Can someone here help me please?

**Comment by mars9180** [comment]
hi, I also met this problem, Seems to have not found libcurl or nghttp2 library problems, I bypassed the problem, the specific operation is as follows:git clone git://github.com/Sensory/alexa-rpi.git

**Comment by sanjayrd** [comment]
@uyanga46,

Could you please follow @mars9180's instructions for now? Otherwise, you can manually download the Sensory repository codebase and upload it to your raspberry pi. We will investigate what seems to be going wrong in the meantime and update as necessary.

Thanks for letting us know!
Sanjay

**Comment by uyanga46** [comment]
@mars9180 Great! It worked. Thanks a lot :)

**Comment by uyanga46** [comment]
@mars9180 Great! It worked. Thanks a lot!  :)
