### ISSUE TITLE
[AVS SDK V1.8] AVS Bluetooth behaviors confirm.

### ISSUE THREAD

**Issue by yyznefu** [alexa/avs-device-sdk#977]
Hi Amazon,

Current AVS SDK support Bluetooth on v1.8, but there are some Bluetooth behaviors need confirm:
1. Does Bluetooth will turn off discover mode after disconnect?
2. If the DUT has connected to Speaker via Bluetooth, Can it be paired with other Bluetooth devices?
3. When Bluetooth connected, power off and then power on, The DUT must be connected via Bluetooth settings manually or voice command?
4. Does DUT NOT automatically connect when in range?
5. Can AVS music and Bluetooth playback switch to each other?

thanks

**Comment by kjkh** [comment]
Hi @yyznefu,

1. Both Scanning and Discoverable modes will exit after the SDK receives an ExitDiscoverableMode directive or if a device is successfully paired. This does not happen after a disconnect.
2. The DUT can have any number of paired devices. When you are connected as a speaker you may pair with another device. However, AVS does not support multiple connected devices. The SDK currently does not forcibly disconnect the second device if a connection happens after the pairing. This will be added in a future release.
3. Yes, you will have to manually reconnect (can be either through voice or settings). In this case there are no directives sent to connect to the previously connected device.
4. No it does not.
5. Yes. If Bluetooth is playing and you ask Alexa to play music, it will stop the Bluetooth playback and vice versa. However, there is no barge-in behavior between each other because they both occupy the Content channel.
