### ISSUE TITLE
Alarm volume not adjusted properly when focus changed

### ISSUE THREAD

**Issue by bjh970913** [alexa/avs-device-sdk#988]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Upon barge-in, the timer alarm sound goes silent. But only 10 seconds. For example when ask about weather, alarm sound plays during alexa is speaking.

## What is the expected behavior?
Alarm volume should go silence during barge-in.
I think when alerts channel lose or gain focus, AlertsCapabilityAgent should adjust AVS_ALERTS_VOLUME properly.

## What behavior are you observing?
Alarm sound replays during speaking.

## Provide the steps to reproduce the issue, if applicable:
Alexa set alarm after 3 seconds.
[Alarm starts playing]
[Barge-in] Alexa, whats the weather like?
[Alexa Speaking] ........ <10 Seconds later alarm sound plays while alexa is still speaking> 

## Tell us about your environment:
OS X, SampleApplication

### What version of the AVS Device SDK are you using?
      <1.8.1>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bjh970913** [comment]
Think update "AlertsCapabilityAgent::executeOnFocusManagerFocusChanged"

Add handling logic for FocusManagerInterface::ALERTS_CHANNEL_NAME

**Comment by dhpp** [comment]
Hi @bjh970913, thanks for asking this question.  This behavior is actually correct - when backgrounded, our Alert logic renders every 10 seconds, instead of more frequently.  Also, the Alerts Capability Agent when backgrounded does not update its volume, it simply renders different audio files which AVS provides.  Those sounds are admittedly very similar to the normal sounds, however this is what the AVS User Experience team has determined is the right thing to do.

I'll close this out.  Feel free to re-open if you have further questions on this topic, thanks.
